<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js">
</script>
<script type="text/javascript" src="https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
<link rel="stylesheet" href="https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css" />
<script type="text/javascript" src="\deeplife\public\js\custom.js"></script>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Schedule and to-do</h5>
            </div>
            <div class="ibox-content">
                <form method="post" name="SamUser" class="" action="" enctype="multipart/form-data" id="SamUser">
                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="usr">Person name</label>
                            <input type="text" class="form-control" id="usr">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="usr">Title</label>
                            <input type="text" class="form-control" id="title">
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="comment">Description</label>
                            <textarea class="form-control" rows="5" id="desc"></textarea>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="usr">Date</label>
                            <div class='input-group date' id='datetimepicker1'>
                                <input type='text' class="form-control" />
                                <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="usr">Time</label>
                            <div class='input-group date' id='datetimepicker2'>
                                <input type='text' class="form-control" />
                                <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-4 text-right">
                            <input type="submit" name="submit" id="submitbutton" class="btn btn-primary" value="Save">
                            <input type="submit" name="submit" id="submitbutton" class="btn btn-default" value="Cancel">
                        </div>
                    </div>
            </div>
            </form>
        </div>
    </div>
</div>
</div>
</div>
</div>


<!-- ------------------------------------------------------------------------------------------------------------------ -->

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Learning</h5>
            </div>
                <div class="ibox-content">
                <ul class="learning">
                    <li>
                        <div class="row">
                            <div class="col-sm-2">
                                <div class="image-holder"></div>
                            </div>
                            <div class="col-sm-8 learn-content">
                                <div class="cell">
                                    <h2>Heading Section</h2>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                </div>
                            </div>
                            <div class="col-sm-2 learn-content">
                                <div class="cell">
                                    <button class="btn btn-primary">View</button>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="row">
                            <div class="col-sm-2">
                                <div class="image-holder"></div>
                            </div>
                            <div class="col-sm-8 learn-content">
                                <div class="cell">
                                    <h2>Heading Section</h2>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                </div>
                            </div>
                            <div class="col-sm-2 learn-content">
                                <div class="cell">
                                    <button class="btn btn-primary">View</button>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="row">
                            <div class="col-sm-2">
                                <div class="image-holder"></div>
                            </div>
                            <div class="col-sm-8 learn-content">
                                <div class="cell">
                                    <h2>Heading Section</h2>
                                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                </div>
                            </div>
                            <div class="col-sm-2 learn-content">
                                <div class="cell">
                                    <button class="btn btn-primary">View</button>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
                </div>
        </div>
    </div>
</div>
