<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Deeplife ' . $this->translate('1.0'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge') ?>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/animate.min.css'))
        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))
    ?>
    <?php echo $this->headScript()->prependFile($this->basePath('js/jquery-2.1.1.js')); ?>
    <?php echo $this->headScript()->prependFile($this->basePath('js/bootstrap.min.js')); ?>

</head>