<div ng-controller="RoleDetailsCtrl">
  <h1><?php echo $this->translate('Role Details'); ?></h1>

  <h3>
    {{currentRole.roleId}}
    <button type="button" title="<?php echo $this->translate('Delete'); ?>"class="btn btn-danger delete pull-right">
      <span class="glyphicon glyphicon-trash"></span> <?php echo $this->translate('Delete'); ?>
    </button>
  </h3>

  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div class="panel-heading" data-toggle="collapse"  data-target="#description">
        <h4 class="panel-title">
          <a href="">
            <?php echo $this->translate('Description'); ?>
          </a>
        </h4>
      </div>
      <div id="description" class="panel-collapse collapse in">

      </div>
    </div>
</div>

<?php
$this->inlineScript()
   ->appendFile($this->basePath() . '/js/vendor/jquery.jeditable.mini.js');
?>
