<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js">
</script>
<script type="text/javascript"
        src="https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/src/js/bootstrap-datetimepicker.js"></script>
<link rel="stylesheet"
      href="https://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/e8bddc60e73c1ec2475f827be36e1957af72e2ea/build/css/bootstrap-datetimepicker.css"/>


<?php
$title = 'Add Schedule';
$this->headTitle($title);
?>


<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?php echo $this->escapeHtml(ucwords($title)); ?>
                    <small></small>
                </h5>
                <div class="ibox-tools">

                </div>
            </div>
            <div class="ibox-content">

                <?php

                $form->setAttribute('method', 'post');
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('action', $this->url('schedule', array('action' => 'add')));
                $form->prepare();
                echo $this->form()->openTag($form);
                foreach ($form as $element) :


                    ?>

                    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
                        <label class=" col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                        <div class="col-sm-4">

                            <?php if ($element->getLabel() === 'Date') { ?>
                                <div class="input-group date" id="datetimepicker1">
                                <?php echo $this->formElement($element);
                                if ($this->formElementErrors($element))
                                    ?>
                                    <span class="input-group-addon">
                                       <span class="glyphicon glyphicon-calendar"> </span></span>
                                    </div>
                                <?php } elseif ($element->getLabel() === 'Time') { ?>
                                <div class="input-group date" id="datetimepicker2">
                                <?php echo $this->formElement($element);
                                if ($this->formElementErrors($element))
                                    ?>
                                    <span class="input-group-addon">
                                       <span class="glyphicon glyphicon-time"> </span></span>
                                    </div>


                                <?php } else { ?>

                                <?php echo $this->formElement($element);
                                if ($this->formElementErrors($element))
                                    ?>

                                    <span class="help-inline   "><?php echo $this->formElementErrors($element) ?></span>
                            <?php } ?>

                        </div>
                    </div>

                    <?php
                endforeach;


                echo $this->form()->closeTag();
                ?>


            </div>
        </div>
    </div>
</div>
<script>
    /*Bootstrap Datetimepicker*/
    $(function () {

        $('#datetimepicker1').datetimepicker({
            format: 'MMM DD YYYY',
            minDate: new Date(),
        });

        $('#datetimepicker2').datetimepicker({
            format: 'LT'
        });


    });
</script>