
<?php echo $this->doctype();  ?>
<html lang="en">
<?php echo $this->render('element-sea/headtitle'); ?>
<body class="." id="page-top">
<?php echo $this->render('element-sea/headnav'); ?>
<?php //echo $this->content; ?>
    <div id="inSlider" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#inSlider" data-slide-to="0" class="active"></li>
            <li data-target="#inSlider" data-slide-to="1"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>Everyone<br/>
                            desciple 5.<br/>
                            <br/>
                        </h1>
                        <p>Aggressively evangelize, deeply build, urgently multiply</p>
                        <p>
                            <a class="btn btn-lg btn-primary" href="#pricing" role="button" style="background-color:#03b2d4 ;">Learn More</a>
                            <!--<a class="caption-link" href="#" role="button">Inspinia Theme</a>-->
                        </p>
                    </div>
                    <!--<div class="carousel-image wow zoomIn">-->
                    <!--<img src="img/laptop.png" alt="laptop"/>-->
                    <!--</div>-->
                </div>
                <!-- Set background for slide in css -->
                <div class="header-back one"></div>

            </div>
            <div class="item">
                <div class="container">
                    <div class="carousel-caption blank">
                        <h1>“Don’t be afraid; <br/> from now on you will be catching men”</h1>

                        <p>Launch deep in the see. </p>
                        <p><a class="btn btn-lg btn-primary" href="#pricing" role="button">Learn more</a></p>
                    </div>
                </div>
                <!-- Set background for slide in css -->
                <div class="header-back two"></div>
            </div>
        </div>
        <a class="left carousel-control" href="#inSlider" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#inSlider" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
<section id="sign-in" class="container services">
    <h1>PACT Landing Page</h1>
    <p>Click HERE to login via TheKey.</p>
</section>
    <section id="sign-in" class="container services">
        <div class="row">
            <div class="col-sm-6">
                <br/><br/><br/>
                <div class="col-sm-8 col-sm-offset-2">
                    <img  src="<?php echo $this->basePath('/img/logooo.png');?>"/>
                </div>
                <div class="col-sm-8 col-sm-offset-2" style="text-align: center;">
                    <h5>Everyone disciple five. </h5>
                </div>
            </div>
            <div class="col-sm-6">

                <!--            <div class="ibox-content">-->
                <!--                <h2 style="text-align: left;">Signin</h2>-->
                <!--                <h4>Log in with Email  or phone number </h4>-->
                <!---->
                <!--                --><?php //if(strlen($flashMessages)):  ?>
                <!--                <span class="help-inline " ><ul>    <li>--><?php //echo $flashMessages; ?><!--</li> </ul>-->
                <!--                    --><?php //endif; ?>
                <!---->
                <!--                    --><?php
                //                    $form = $this->loginForm;
                //                    $form->prepare();
                //                    $form->setAttribute('action', $this->url('zfcuser/login'));
                //                    $form->setAttribute('method', 'post');
                //                    $form->setAttribute('class', 'm-t');
                //                    ?>
                <!--                    --><?php //echo $this->form()->openTag($form) ?>
                <!--                    <div class="form-group --><?php //if($this->formElementErrors($element)) echo "has-error" ?><!--">-->
                <!--                         --><?php //echo $this->formElement ( $form->get('identity')->setAttribute('class', 'form-control') );
                //                         if ($this->formElementErrors ( $form->get('identity') ))
                //                         ?>
                <!--                        <span class="help-inline  error ">--><?php //echo $this->formElementErrors($form->get('identity')) ?><!--</span>-->
                <!---->
                <!--                        </div>-->
                <!--                        <div class="form-group">-->
                <!--                           --><?php //echo $this->formElement ( $form->get('credential')->setAttribute('class', 'form-control') );
                //                           if ($this->formElementErrors ( $form->get('credential') ))
                //                           ?>
                <!--                            <span class="help-inline  error ">--><?php //echo $this->formElementErrors($form->get('credential')) ?><!--</span>-->
                <!---->
                <!---->
                <!--                        </div>-->
                <!--                        <button type="submit" class="btn btn-primary block btn btn-info col-md-12 full-width m-b">Login</button>-->
                <!---->
                <!--                    --><?php //if ($this->enableRegistration) : ?>
                <!--                        Not registered? <a href="--><?php //echo $this->url('signup') ?><!--">Sign up!</a>-->
                <!--                     Forgot password? <a data-toggle="modal" data-target="#myajaxforgot" >Forgot password!</a>-->
                <!--                    --><?php //endif; ?>
                <!---->
                <!--                    --><?php //echo $this->form()->closeTag() ?>
                <!---->
                <!---->
                <!--            </div>-->
                <!--        </div>-->
            </div>

    </section>
    <section  id="features" class="container features">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>Ultimate growth<br/> <span class="navy"> with high class features</span> </h1>
                <p>Reach the globe with the spirit of God's Word. </p>
            </div>
        </div>
        <section id="about">
            <div class="row">
                <div class="col-md-3 text-center wow fadeInLeft">
                    <div>
                        <span class="glyphicon glyphicon-user" style="font-size: 250%; Color:deepskyblue;"></span>
                        <h2>Win</h2>
                        <p>“The fruit of the righteous is a tree of life; and he that winneth souls is wise.” Proverbs 11:30</p>
                    </div>
                    <div class="m-t-lg">
                        <span class="glyphicon glyphicon-road" style="font-size: 250%; Color:deepskyblue;"></span>
                        <h2>Build</h2>
                        <p>And let us consider how to stir up one another to love and good works, not neglecting to meet together, as is the habit of some, but encouraging one another, and all the more as you see the Day drawing near. Hebrews 10:24-25</p>
                    </div>
                </div>
                <div class="col-md-4 col-sm-offset-1 text-center  wow zoomIn">
                    <img src="<?php echo $this->basePath('/img/logooo.png');?>" alt="dashboard" class="img-responsive">
                </div>
                <div class="col-md-3 text-center wow fadeInRight">
                    <div>
                        <span class="glyphicon glyphicon-send" style="font-size: 250%; Color:deepskyblue;"></span>
                        <h2>Send</h2>
                        <p>... And how can they believe in the One of whom they have not heard? And how can they hear without someone to preach? And how can they preach unless they are sent? As it is written: “How beautiful are the feet of those who bring good news!”        Romans 10:14-15</p>
                    </div>
                    <div class="m-t-lg">
                        <span class="glyphicon glyphicon-cloud" style="font-size: 250%; Color:deepskyblue;"></span>
                        <h2>Track</h2>
                        <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus.</p>
                    </div>
                </div>
            </div>
            <section id="pricing"></section>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="navy-line"></div>
                    <h1>Message</h1>
                    <!--<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. </p>-->
                </div>
                <div class="row features-block">
                    <div class="col-lg-6 text-right wow fadeInRight">


                        <img src="<?php echo $this->basePath('/img/dash.jpg');?>" alt="dashboard"  class="img-circle">
                        <!--                    <img src="" class="img-responsive pull-right">-->
                    </div>
                    <div class="col-lg-6 features-text wow fadeInLeft">
                        <!--<small>INSPINIA</small>-->
                        <h2>Message from the SEA leader  </h2>
                        <p>It is not a strange thing to hear the statement, “African
                            Christianity is a mile wide but an inch deep.” This is to say that
                            African church growth focuses mostly on quantity than quality.
                            There could be lots of energy, time and resources put into
                            expansion, coverage, and exposure through evangelism when
                            compared to helping someone to truly follow Christ, get grounded in
                            the faith and take deep root in the word of God and lead a transformed,
                            authentic and Christ-like life style in private and public arenas.
                            As an organization, Campus Crusade for Christ seeks to produce true followers of
                            Jesus. It received its mandate from our Lord and savior Jesus Christ to “go…and
                            make disciples of all nations” (Matthew 28:19). In collaboration with the body of Christ,
                            the ministry desires to contribute meaningfully in becoming a “salt and light” to the
                            problem for the glory of God. It is out of such genuine desire that the vision of “Deep
                            Life” has been born. Our goal is to train and equip 100, 000 leaders who shall be
                            planting and building 100,000 churches on cities, villages, campuses,
                            student population centers, market places, and online networks.
                            This vision has 3 phases of implementation. Feb 10 – 31 Dec 2014 shall
                            be a time of prayer and preparation. Jan 1 – 31 Dec 2015 will be a
                            year of mobilization and training. Jan 1- Oct 10/2016 shall be a
                            time of full implementation and accelerated actions across
                            the 24 countries of the Southern and Eastern Africa in 240
                            locations.</p>
                        <!--<a href="" class="btn btn-primary">Learn more</a>-->
                    </div>

                </div>
                <div class="col-lg-12 text-center">
                    <div class="navy-line"></div>
                    <h1>About Deep life</h1>
                    <!--<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. </p>-->
                </div>
                <div class="row features-block">
                    <div class="col-lg-6 features-text wow fadeInLeft">
                        <!--<small>INSPINIA</small>-->
                        <h2>Launch out to the deep. </h2>
                        <p>It is not a strange thing to hear the statement, “African
                            Christianity is a mile wide but an inch deep.” This is to say that
                            African church growth focuses mostly on quantity than quality.
                            There could be lots of energy, time and resources put into
                            expansion, coverage, and exposure through evangelism when
                            compared to helping someone to truly follow Christ, get grounded in
                            the faith and take deep root in the word of God and lead a transformed,
                            authentic and Christ-like life style in private and public arenas.
                            As an organization, Campus Crusade for Christ seeks to produce true followers of
                            Jesus. It received its mandate from our Lord and savior Jesus Christ to “go…and
                            make disciples of all nations” (Matthew 28:19). In collaboration with the body of Christ,
                            the ministry desires to contribute meaningfully in becoming a “salt and light” to the
                            problem for the glory of God. It is out of such genuine desire that the vision of “Deep
                            Life” has been born. Our goal is to train and equip 100, 000 leaders who shall be
                            planting and building 100,000 churches on cities, villages, campuses,
                            student population centers, market places, and online networks.
                            This vision has 3 phases of implementation. Feb 10 – 31 Dec 2014 shall
                            be a time of prayer and preparation. Jan 1 – 31 Dec 2015 will be a
                            year of mobilization and training. Jan 1- Oct 10/2016 shall be a
                            time of full implementation and accelerated actions across
                            the 24 countries of the Southern and Eastern Africa in 240
                            locations.</p>
                        <!--<a href="" class="btn btn-primary">Learn more</a>-->
                    </div>
                    <div class="col-lg-6 text-right wow fadeInRight">
                        <img src="<?php echo $this->basePath('/img/dash.jpg');?>" alt="dashboard" class="img-responsive pull-right">
                    </div>
                </div>
                <p class="m-t" style="align-content: center"> <small>Deep-Life &copy; 2014</small> </p>
            </div>

        </section>
    </section>
    <div class="loginColumns animated fadeInDown">
        <div class="row">

            <div class="col-md-6">
                <div class="ibox-content">
                </div>
            </div>
        </div>
        <hr/>

    </div>
    <style>
        span.help-inline ul li {
            color: red;
            list-style: none;

        }
    </style>
<?php echo $this->render('element-sea/footer'); ?>
</body>
</html>