<?php
$title = 'Edit Question';
$this->headTitle($title);
?>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?php echo $this->escapeHtml(ucwords($title)); ?>
                    <small></small>
                </h5>
                <div class="ibox-tools">

                </div>
            </div>
            <div class="ibox-content">

                <?php

                $form->setAttribute('method', 'post');
                $form->setAttribute('class', 'form-horizontal');


                $form->setAttribute('action', $this->url(
                    'movement',
                    array(
                        'action' => 'edit',
                        'id' => $this->id,
                    )
                ));
                $form->prepare();
                echo $this->form()->openTag($form);
                foreach ($form as $element) :
                    ?>
                    <div class="form-group <?php if ($this->formElementErrors($element)) echo "error" ?>">
                        <label class=" col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
                        <div class="col-sm-10">
                            <?php echo $this->formElement($element);
                            if ($this->formElementErrors($element))
                            ?>
                            <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <?php
                endforeach;


                echo $this->form()->closeTag();
                ?>


            </div>
        </div>
    </div>
</div>