<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
<?php
$title = 'Movement Question';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?php echo $title; ?> </h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-sm-9 m-b-xs">
                        <a href="<?php echo $this->url('movement', array('action' => 'add')); ?>"
                           class="btn  btn-sm btn-secondary">Add Question</a>

                        </p>
                    </div>
                    <div class="col-sm-3">

                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-hover dataTables">
                        <thead>
                        <tr>

                            <th>Question</th>
                            <th>Country</th>
                            <th>Category</th>
                            <th>Mandatory</th>
                            <th>ACTION</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php


                        $cout = 1;
                        foreach ($questions as $question) : ?>
                            <tr>

                                <td><?php echo $this->escapeHtml(ucwords($question->question)); ?></td>
                                <td><?php
                                    if ($question->default_question) {
                                        echo $this->escapeHtml(ucwords('Default Question'));

                                    } else {
                                        echo $this->escapeHtml(ucwords(strtolower($countries[$question->country])));

                                    }


                                    ?>


                                </td>
                                <td>


                                    <?php
                                    $stage = strtolower($question->category);
                                    $class = '';
                                    switch ($stage) {

                                        case 'build':
                                            $class = 'btn-warning';
                                            break;
                                        case 'win':
                                            $class = 'btn-primary';
                                            break;
                                        case 'send':
                                            $class = 'btn-info';
                                            break;

                                        case 'added':
                                        default:
                                            $class = 'btn-danger';
                                            break;


                                    }

                                    ?>

                                    <a class="fbox tips btn btn-xs <?php echo $class ?> ">
                                        <?php echo $this->escapeHtml($question->category == '' ? 'ADDED' : strtoupper($question->category)); ?></a>


                                </td>

                                <td>

                                    <?php
                                    $stage = strtolower($question->mandatory);
                                    $class = '';
                                    switch ($stage) {

                                        case '0':
                                            $class = 'btn-danger';
                                            break;
                                        case '1':
                                            $class = 'btn-primary';
                                            break;


                                    }

                                    ?>

                                    <a class="fbox tips btn btn-xs <?php echo $class ?> ">
                                        <?php echo $this->escapeHtml($question->mandatory == 1 ? 'Yes' : 'No'); ?></a>

                                </td>

                                <td><span class="action">
<a href="<?php echo $this->url('movement',
    array('action' => 'edit', 'id' => $question->id)); ?>" class="tips" title="Edit"><i class="fa fa-edit"></i> </a>
   <span>&#x7C;</span>
       <a href="<?php echo $this->url('movement',
           array('action' => 'delete', 'id' => $question->id)); ?>"
          onclick="return confirm('Are you sure you want to delete this item?');" class="tips" title="Delete"> <i
               class="fa fa-trash-o"></i></a>
   	</span>
                                </td>

                            </tr>
                        <?php endforeach; ?>

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

</div>

<?php echo $this->headScript()
    ->prependFile($this->basePath('js/plugins/dataTables/jquery.dataTables.min.js'));


?>

<script>
    $(document).ready(function () {
        $('.dataTables').dataTable({
            "order": [[0, "asc"]],
            "columnDefs": [{"targets": 4, "orderable": false}],
        });

    });
</script>



