   <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
  <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5><?php echo $this->translate('Testimonial Tools')?></h5>
       </div>
        <div class="ibox-content">
            <div class="row">
                <div class="col-sm-1 m-b-xs">
         
                </div>
                <div class="col-offset-sm-8">
                 
                </div>
            </div>
                  <div class="table-responsive">
                <table class="table table-striped  table-hover dataTables">
                    <thead>
                    <tr>
                        <th class="nodisplay" ></th>
                        <th><?php echo $this->translate('DESCRIPTION')?> </th>
                          <th><?php echo $this->translate('STATUS')?></th>
                        <th><?php echo $this->translate('ACTION')?></th>
                  </tr>
                    </thead>
                    <tbody>
                    
                    <?php  $isno=1;?>
                <?php  foreach ($testimonials as $testimonial) : ?>
                <tr> 
                 <td class="nodisplay" ></td>
                         <td><?php echo $this->escapeHtml($testimonial->description);?></td>
                         <td><?php                         
                         if($testimonial->status==1){
                             echo '<span class="label label-info pull-left">'.$this->translate('Approved').'</span>';
                         }elseif($testimonial->status==2){
                          echo '<span class="label label-danger pull-left">'.$this->translate('Rejected').'</span>';   
                         }else {
                             echo '<span class="label label-warning pull-left">'.$this->translate('Waiting').'</span>'; 
                         }
                          ?>
                             
                             
                         </td>
                            
                         <td>
<a href="<?php echo $this->url('testimonial',
            array('action'=>'edit', 'id' => $testimonial->id));?>" class="tips " title="Edit">
           <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
             </a><span>&#x7C;</span><a href="<?php echo $this->url('testimonial',
            array('action'=>'delete', 'id' => $testimonial->id));?>" onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?')?>');" class="tips  " title="Delete"> <i class="fa fa-trash-o" aria-hidden="true"></i></a>
   	
</td>
                
            </tr>
        <?php endforeach; ?>
                 
                    </tbody>
                </table>
            </div></div>
            
          
        </div>
        </div>
        </div>

          <?php echo $this->headScript()
 ->prependFile($this->basePath('js/plugins/dataTables/jquery.dataTables.min.js')) ;
  
  
 ?>

 <script>
        $(document).ready(function() {
            $('.dataTables').dataTable({
        "order": [[ 0, "asc" ]],
       "columnDefs": [ {"targets": 3,"orderable": false} ],
            });
             
             });
 </script> 
