<div>
    <?php echo $this->partial('rnav'); ?>
    <?php echo $this->partial('headnav'); ?>

    <div id="page-wrapper" class="gray-bg">
        <!--top navigation-->

        <?php echo $this->partial('headtitle'); ?>
        <?php echo $this->partial('profile'); ?>


        $file= $this->paramfile;
        header (“Content-type: octet/stream”);
        header (“Content-disposition: attachment; filename=”.$file.“;”);
        header(“Content-Length: “.filesize($file));
        readfile($file);


    </div>
    <?php echo $this->partial('footer'); ?>
    </div>