<div><div class="row border-bottom">
    <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <a class="navbar-minimalize minimalize-styl-2" href="#"><i class="fa fa-bars"></i> </a>
          
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li>
                <span class="m-r-sm text-muted welcome-message"><?php echo $this->translate('Welcome To DeepLife Discipleship System'); ?>
               
                </span>
            </li>
            <li>
                <a href="<?php echo $this->url('zfcuser/logout') ?>">
                    <i class="fa fa-sign-out"></i><?php echo $this->translate('Log out'); ?>
                </a>
            </li>
        </ul>

    </nav>
</div>
</div>
