
<!--headtitle-->
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Welcome <!-- Test if the User is connected -->
            <?php if(!$this->zfcUserIdentity()): ?>
                <!-- display the login form -->
                <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
            <?php else: ?>
                <!-- display the 'display name' of the user -->
                <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
            <?php endif?> </h2>
        <ol class="breadcrumb">
            <li>
                <a href="<?php echo $this->Url ?>">Home</a>
            </li>
            <li class="active">
                <strong><?php echo $this->title ?></strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">


    </div>
</div>
