<div class="row animated bounceInDown">
<div class="row">
    <div class="col-lg-3">
        <div class="widget style1">
            <div class="row">
                <div class="col-xs-4 text-center">
                    <i class="fa fa-tree fa-5x"></i>
                </div>
                <div class="col-xs-8 text-right">
                    <span> Disciples Tree  </span>
                    <h2 class="font-bold">42</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="btn btn-w-m btn-primary" href="news " >
        <a  href="news " </a>
    <div class="col-lg-3"  href="news " >
        <div class="widget style1 navy-bg" href="news">
            <div class="row">
                <div class="col-xs-4" >
                    <i class="fa fa-newspaper-o fa-5x"></i>
                </div>
                <div class="col-xs-8 text-right">
                    <span> News  </span>

                  <a  href="news " </a>
                    <h2 class="font-bold">26</h2>
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="col-lg-3">
        <div class="widget style1 lazur-bg">
            <div class="row">
                <div class="col-xs-4">
                    <i class="fa fa-envelope-o fa-5x"></i>
                </div>
                <div class="col-xs-8 text-right">
                    <span> New messages </span>
                    <h2 class="font-bold">260</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="widget style1 yellow-bg">
            <div class="row">
                <div class="col-xs-4">
                    <i class="fa fa-bell fa-5x"></i>
                </div>
                <div class="col-xs-8 text-right">
                    <span> New notification </span>
                    <h2 class="font-bold">12</h2>
                </div>
            </div>
        </div>
    </div>
</div>
    </div>