<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Deeplife '. $this->translate('1.0'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('dash/css/style.css'))
        ->prependStylesheet($this->basePath('dash/css/animate.css'))
        ->prependStylesheet($this->basePath('dash/font-awesome/css/font-awesome.cs'))
        ->prependStylesheet($this->basePath('dash/css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('dash/css/bootstrap.min.css')) ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath('dash/js/jquery-2.1.1.js'))
        ->prependFile($this->basePath('dash/js/plugins/metisMenu/jquery.metisMenu.js'))
        ->prependFile($this->basePath('dash/js/inspinia.js'))
        ->prependFile($this->basePath('dash/js/plugins/slimscroll/jquery.slimscroll.min.js'))
        ->prependFile($this->basePath('dash/js/plugins/pace/pace.min.js'))
        ->prependFile($this->basePath('dash/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('dash/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))

    ; ?>

</head>
<body>
<div id="wrapper">

    <?php echo $this->content; ?>


</div> <!-- /container -->
<?php echo $this->inlineScript() ?>

</body>
</html>
