<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Deeplife '. $this->translate('1.0'))->setSeparator(' - ')->setAutoEscape(false) ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')?>
    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/animate.min.css'))
        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))
    ?>
    <?php echo $this->headScript()->prependFile($this->basePath('js/jquery-2.1.1.js')) ; ?>
    <?php echo $this->headScript()->prependFile($this->basePath('js/bootstrap.min.js')) ; ?>

</head>



        <?php echo $this->render('index/signup'); ?>
        <?php echo $this->content; ?>


<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Scripts -->

<?php echo $this->inlineScript()->prependFile($this->basePath('js/pace.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/classie.js'))
    ->prependFile($this->basePath('js/cbpAnimatedHeader.js'))
    ->prependFile($this->basePath('js/wow.min.js'));
//->prependFile($this->basePath('js/inspinia.js'));

?>
</body>