<div class="row">


    <div class="col-lg-4">
        <div class="widget-head-color-box navy-bg p-lg text-center">
            <div class="m-b-md">
                <h3 class="font-bold no-margins">
                    Your Mentor
                </h3> <h2 class="font-bold no-margins">
                    Alex Smith
                </h2>
                <small>Founder of Groupeq</small>
            </div>
            <img src="../img/a4.jpg" class="img-circle circle-border m-b-md" alt="profile">
            <div>
                <span>100 Tweets</span> |
                <span>350 Following</span> |
                <span>610 Followers</span>
            </div>
        </div>
        <div class="widget-text-box">
            <h4 class="media-heading">Alex Smith</h4>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
            <div class="text-right">
                <a class="btn btn-xs btn-primary"><i class="fa fa-mail-reply"></i> Message</a>
            </div>
        </div>
    </div>

</div>