

        <div class="col-md-6">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Profile Detail</h5>
                </div>
                <div>
                    <div class="widget-head-color-box navy-bg p-lg text-center">
                                <div class="m-b-md">
                                    <h3 class="font-bold no-margins">
                                        <?php echo $this->zfcUserIdentity()->getEmail(); ?>
                                    </h3> <h2 class="font-bold no-margins">
                                        <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
                                    </h2>
                                    <small> <?php echo $this->zfcUserIdentity()->getCountry(); ?></small>
                                </div>
                                <img src="../img/a4.jpg" class="img-circle circle-border m-b-md" alt="profile">
                                <div>
                                    <span>100 Tweets</span> |
                                    <span>350 Following</span> |
                                    <span>610 Followers</span>
                                </div>
                            </div>
                            <div class="widget-text-box">
                                <h4 class="media-heading"> <?php echo $this->zfcUserIdentity()->getDisplayname(); ?></h4>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                <h2>
                                    <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
                                </h2>
                                <ul class="list-unstyled m-t-md">
                                    <li>
                                        <span class="fa fa-envelope m-r-xs"></span>
                                        <label>Email:</label>
                                        <?php echo $this->zfcUserIdentity()->getEmail(); ?>
                                    </li>
                                    <li>
                                        <span class="fa fa-home m-r-xs"></span>
                                        <label>Country:</label>
                                        <?php echo $this->zfcUserIdentity()->getCountry(); ?>
                                    </li>
                                    <li>
                                        <span class="fa fa-phone m-r-xs"></span>
                                        <label>Contact:</label>
                                        <?php echo $this->zfcUserIdentity()->getPhoneno(); ?>
                                    </li>
                                </ul>
                                <div class="text-right">
                                    <a class="btn btn-xs btn-primary"><i class="fa fa-mail-reply"></i> Message</a>
                                </div>
                            </div>


                    </div>
                </div>

            </div>

