<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element"> <span>
                            <img alt="image" class="img-circle" style="ima" src="
                        <?php if(!$this->zfcUserIdentity()): ?>
                            <?php echo $this->zfcUserLoginWidget(array('redirect'=>'application')); ?>
                        <?php else: ?>
                            <?php echo $this->zfcUserIdentity()->getPicture(); ?>
                        <?php endif?>"
                             </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs">
                                            <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
                                    </strong>
                             </span> <span class="text-muted text-xs block">Missionarry <b class="caret"></b></span> </span> </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="/Dashboard/profile.html">Profile</a></li>
                        <li><a href="http://localhost:63342/Dashboard/contacts.html">Notifications</a></li>
                        <li><a href="http://localhost:63342/Dashboard/mailbox.html">Messages</a></li>
                        <li class="divider"></li>
                        <li><a href="http://localhost:63342/Dashboard/login.html">Logout</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    Deeplife
                </div>
            </li>
            <li class="active">
                <a href="http://localhost:63342/Dashboard/index.html"><i class="fa fa-th-large"></i> <span class="nav-label">Dashboards</span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse in">
                    <li class="active"><a href="<?php echo $this->url('application') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">User Dashboard</a></li>
                    <li><a href="<?php echo $this->url('application') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Settings</a></li>

                </ul>
            </li>

            <li>
                <a href="#"><i class="fa fa-bar-chart-o"></i> <span class="nav-label">Disciples</span><span class="fa arrow"></span></a>
                <ul class="nav nav-second-level collapse">
                    <li><a href="<?php echo $this->url('application') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Add</a></li>
                    <li><a href="<?php echo $this->url('application') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">List</a></li>

                </ul>
            </li>

            <li class="">
                <a href="http://deeplife.cccsea.org/#/layouts%20target="><i class="fa fa-magic"></i> <span class="nav-label">Win </span><span class="label label-info pull-right">62</span></a>
            </li>
            <li>
                <a target="_blank" href="http://deeplife.cccsea.org/#/widgets"><i class="fa fa-magic"></i> <span class="nav-label">Build</span><span class="label label-info pull-right">62</span></a>
            </li>
            <li>
                <a target="_blank" href="http://deeplife.cccsea.org/#/grid_options"><i class="fa fa-magic"></i> <span class="nav-label">Send</span><span class="label label-info pull-right">62</span></a>
            </li>
            <li class="special_link">
                <a href="http://localhost:63342/Dashboard/index.html"><i class="fa fa-database"></i> <span class="nav-label">Tree</span></a>
            </li>
        </ul>

    </div>
</nav>
