
<div class="col-lg-2">
    <div class="widget navy-bg p-lg text-center">
        <div class="m-b-md">
            <i class="fa fa-shield fa-4x"></i>
            <h1 class="m-xs">456</h1>
            <h3 class="font-bold no-margins">
                WIN
            </h3>
            <small>Aggressively</small>
        </div>
    </div>
</div>
<div class="col-lg-2">
    <div class="widget yellow-bg p-lg text-center">
        <div class="m-b-md">
            <i class="fa fa-building fa-4x"></i>
            <h1 class="m-xs">520</h1>
            <h3 class="font-bold no-margins">
                BUILD
            </h3>
            <small>Deeply</small>
        </div>
    </div>

</div>
<div class="col-lg-2">
    <div class="widget navy-bg p-lg text-center">
        <div class="m-b-md">
            <i class="fa fa-send fa-4x"></i>
            <h1 class="m-xs">456</h1>
            <h3 class="font-bold no-margins">
                SEND
            </h3>
            <small>Urgently</small>
        </div>
    </div>
</div>
