<div class="col-lg-2">
    <div class="widget navy-bg p-lg text-center">
        <div class="m-b-md">
            <i class="fa fa-shield fa-4x"></i>
            <h1 class="m-xs">456</h1>
            <h3 class="font-bold no-margins">
                WIN
            </h3>
            <small>Aggressively</small>
        </div>
    </div>
</div>
<div class="col-lg-2">
    <div class="widget yellow-bg p-lg text-center">
        <div class="m-b-md">
            <i class="fa fa-building fa-4x"></i>
            <h1 class="m-xs">520</h1>
            <h3 class="font-bold no-margins">
                BUILD
            </h3>
            <small>Deeply</small>
        </div>
    </div>

</div>
<div class="col-lg-2">
    <div class="widget navy-bg p-lg text-center">
        <div class="m-b-md">
            <i class="fa fa-send fa-4x"></i>
            <h1 class="m-xs">456</h1>
            <h3 class="font-bold no-margins">
                SEND
            </h3>
            <small>Urgently</small>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-3">
        <div class="widget style1">
            <div class="row">
                <div class="col-xs-4 text-center">
                    <i class="fa fa-tree fa-5x"></i>
                </div>
                <div class="col-xs-8 text-right">
                    <span> Disciples Tree  </span>
                    <h2 class="font-bold">42</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="widget style1 navy-bg">
            <div class="row">
                <div class="col-xs-4">
                    <i class="fa fa-newspaper-o fa-5x"></i>
                </div>
                <div class="col-xs-8 text-right">
                    <span> News </span>
                    <h2 class="font-bold">26</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="widget style1 lazur-bg">
            <div class="row">
                <div class="col-xs-4">
                    <i class="fa fa-envelope-o fa-5x"></i>
                </div>
                <div class="col-xs-8 text-right">
                    <span> New messages </span>
                    <h2 class="font-bold">260</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="widget style1 yellow-bg">
            <div class="row">
                <div class="col-xs-4">
                    <i class="fa fa-bell fa-5x"></i>
                </div>
                <div class="col-xs-8 text-right">
                    <span> New notification </span>
                    <h2 class="font-bold">12</h2>
                </div>
            </div>
        </div>
    </div>
</div>