<link rel="stylesheet" href="<?php echo $this->basePath('js/plugins/jcrop/Jcrop.css') ?>" type="text/css">
<?php echo $this->headScript()->prependFile($this->basePath('js/plugins/jcrop/Jcrop.js')) ;?>
<div class="row">
<div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5><?php echo $this->escapeHtml(ucwords($title)); ?> <small></small></h5>

                        </div>
                        <div class="ibox-content">



                            <?php

$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('enctype', 'multipart/form-data');
$form->setAttribute('action', $this->url('disciples', array('action' => 'edit', 'id' => $id)));
$form->prepare();
echo $this->form()->openTag($form); ?>


<?php foreach ( $form as $element ) :

if($element->getLabel()=='Picture'){ ?>

    <div    class="form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">
        <label class=" col-sm-2 col-md-1 control-label"><?php echo $element->getLabel() ?></label>
        <div class="col-sm-4 col-md-4">
            <?php echo $this->formElement ( $element );
            if ($this->formElementErrors ( $element ))
            ?>
            <span class="help-inline  error "><?php echo $this->formElementErrors($element) ?></span>
        </div>
        <input type="hidden" name="x" id="cropx" value="0" />
        <input type="hidden" name="y" id="cropy" value="0" />
        <input type="hidden" name="w" id="cropw" value="0" />
        <input type="hidden" name="h" id="croph" value="0" />
       <div> <img id="image-preview1"   style="display: none;" /></div>
    </div>

    <div class="row" id="profile_hide" >
        <div class="col-sm-8 col-xs-12">
            <div class="profile-pic">

                <div class="form-photo">
                    <?php $avatar='/avatar/noavatar.jpg';
                    if(strlen($image)){
                        $avatar=$image;
                    }

                    ?>

                    <img id="image-preview" src="<?php echo $this->basePath($avatar)?>" width="100" height="100" alt="" />

                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h4>Personal Information</h4>
        </div>
    </div>



<?php }else {?>

<div    class="form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">

        <label class=" col-sm-2 col-md-1 control-label"><?php echo $this->translate($element->getLabel()) ?></label>
        <div class="col-sm-4 col-md-4">
                <?php echo $this->formElement ( $element );
                    if ($this->formElementErrors ( $element ))
                ?>
    <span class="help-inline  error "><?php echo $this->formElementErrors($element) ?></span>
        </div>
 </div>


<?php }
endforeach;


echo $this->form()->closeTag();
?>









                        </div>
                    </div>
                </div>
</div>
<style>
span.help-inline ul li {
  color: red;
  list-style: none;

}
</style>
<script type="text/javascript">
    $('#image-preview1').Jcrop({ boxwidth:300 ,boxHeight:270, onSelect: updateCoords });
    function updateCoords(c)
    {
        $('#cropx').val(c.x);
        $('#cropy').val(c.y);
        $('#cropw').val(c.w);
        $('#croph').val(c.h);

    };
    function readURL(input) {
        if (input.files) {
            var reader = new FileReader();

            reader.onload = function(e) {

                $('#image-preview1').attr('src', e.target.result).show();
                $('#image-preview').attr('src', e.target.result).hide();
                $('#profile_hide').attr('display','none');

            }


            reader.readAsDataURL(input.files[0]);
        }
    }
    $("#inputFile").change(function() {
        readURL(this);

    });

              $('#country').on('change', function() {
     $("#countrycode").val($(this).val());
});


        </script>




