<div>

    <?php echo $this->partial('rnav'); ?>

    <?php echo $this->partial('headnav'); ?>
</div>
<div id="page-wrapper" class="gray-bg">
    <!--top navigation-->

    <?php echo $this->partial('headtitle'); ?>
<h1>Edit News Post</h1>

<?php

/** @var $form \news\Form\Add */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('title')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('slug')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('content')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('category_id')); ?>
</div>

<?php echo $this->formHidden($form->get('id')); ?>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>


    <?php echo $this->partial('footer'); ?>


</div>
