<?php
$title = 'Share Question';
$this->headTitle($title);

?>
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5><?php echo $title; ?> </h5>
            </div>
            <div class="ibox-content">

                <div class="row">
                    <div class="col-sm-12">
                        <a href="<?php echo $this->url('share', array('action' => 'index', 'id' => '1')); ?>">
                            <div class="share-widget style1 <?php if ($share == 1) {
                                echo 'yellow-bg';
                            } else {
                                echo 'inactive';
                            } ?> ">
                                <i class="fa-win"></i>
                                Win
                            </div>
                        </a>
                        <a href="<?php echo $this->url('share', array('action' => 'index', 'id' => '2')); ?>">
                            <div class="share-widget style1 <?php if ($share == 2) {
                                echo 'blue-bg';
                            } else {
                                echo 'inactive';
                            } ?> ">
                                <i class="fa-build"></i>
                                Build
                            </div>
                        </a>
                        <a href="<?php echo $this->url('share', array('action' => 'index', 'id' => '3')); ?>">
                            <div class="share-widget style1 <?php if ($share == 3) {
                                echo 'green-bg';
                            } else {
                                echo 'inactive';
                            } ?>">
                                <i class="fa-send"></i>
                                Send
                            </div>
                            <a>
                    </div>
                </div>
                <form method="post" name="fshare" action="" id="fshare">
                    <div class="form-group ">
                        <div class="table-responsive">
                            <table class="table table-striped table-hover nowrap share-table ">
                                <thead>
                                <tr>
                                    <th> Sno.</th>
                                    <th> Question</th>
                                    <th> Category</th>
                                    <th> Answers</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php $snCounter = 1;
                                foreach ($questions as $question) { ?>
                                    <tr>
                                        <td><?php echo $snCounter++; ?></td>
                                        <td>
                                            <?php echo $this->escapeHtml(ucwords($question->question)); ?>

                                        </td>
                                        <td>
                                            <?php if ($sharetext === 'SEND') { ?>
                                                <a class="fbox tips btn btn-xs green-bg ">SEND</a>
                                            <?php } else if ($sharetext === 'BUILD') { ?>
                                                <a class="fbox tips btn btn-xs blue-bg ">BUILD</a>
                                            <?php } else { ?>
                                                <a class="fbox tips btn btn-xs yellow-bg ">WIN</a>
                                            <?php } ?>
                                        </td>


                                        <td>
                                            <span class="arrow-left addButton"
                                                  attrid="<?php echo $question->id ?>"></span> <span
                                                class="increament-box">
    
   
     <input type="text"
            oninput="this.value = this.value.replace(/[^0-9.]/g, ''); this.value = this.value.replace(/(\..*)\./g, '$1');"
            size="3" name="box[<?php echo $question->id ?>]" id="<?php echo $question->id ?>"
            value="<?php echo(isset($answerData[$question->id]) ? $answerData[$question->id] : 0) ?>">
                        </span>
                                            <span class="arrow-right subButton"
                                                  attrid="<?php echo $question->id ?>"></span>
                                        </td>


                                    </tr>

                                <?php } ?>
                                <tr>
                                    <td colspan="4">
                                        <input name="submit" type="submit" id="submitbutton"
                                               class="btn btn-primary pull-right" value="Save">
                                    </td>
                                </tr>

                                </tbody>
                            </table>
                        </div>
                </form>
            </div>

        </div>
    </div>

</div>


<script>

    $(document).ready(function () {

        $('.subButton').click(function () {
            var id = $(this).attr('attrid');
            var counter = $('#' + id).val();
            counter++;
            $('#' + id).val(counter);
        });
        $('.addButton').click(function () {
            var id = $(this).attr('attrid');
            var counter = $('#' + id).val();
            if (counter > 0) {
                counter--;
            }
            $('#' + id).val(counter);

        });


    });

</script>

