   <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
  <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Learning Tools</h5>
       </div>
        <div class="ibox-content">
            <div class="row">
                <div class="col-sm-1 m-b-xs">
          <a href="<?php echo $this->url('learn',
            array('action'=>'add'));?>" class="btn  btn-sm btn-secondary">Add Learn</a>
                </div>
                <div class="col-offset-sm-8">
                 
                </div>
            </div>
                  <div class="table-responsive">
                <table class="table table-striped  table-hover dataTables">
                    <thead>
                    <tr>
                         <th class="nodisplay" ></th>
                        <th><?php echo $this->translate('TITLE')?></th>
                        <th><?php echo $this->translate('DESCRIPTION')?> </th>
                        <th><?php echo $this->translate('ACTION')?></th>
                  </tr>
                    </thead>
                    <tbody>
                    
                    <?php  $isno=1;?>
                <?php  foreach ($learning as $learn) : ?>
                <tr> 
                 <td class="nodisplay" ></td>
                <td ><?php echo $this->escapeHtml(ucwords($learn->title));?></td>
                <td><?php echo $this->escapeHtml($learn->description);?></td>
                         <td>
<a href="<?php echo $this->url('learn',
            array('action'=>'edit', 'id' => $learn->id));?>" class="tips " title="Edit">
           <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
             </a><span>&#x7C;</span><a href="<?php echo $this->url('learn',
            array('action'=>'delete', 'id' => $learn->id));?>" onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?')?>');" class="tips  " title="Delete"> <i class="fa fa-trash-o" aria-hidden="true"></i></a>
   	
</td>
                
            </tr>
        <?php endforeach; ?>
                 
                    </tbody>
                </table>
            </div></div>
            
          
        </div>
        </div>
        </div>

          <?php echo $this->headScript()
 ->prependFile($this->basePath('js/plugins/dataTables/jquery.dataTables.min.js')) ;
  
  
 ?>

 <script>
        $(document).ready(function() {
            $('.dataTables').dataTable({
        "order": [[ 0, "asc" ]],
       "columnDefs": [ {"targets": 2,"orderable": false} ],
            });
             
             });
 </script> 
