<div class="row">
<div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5><?php echo $this->escapeHtml(ucwords($title)); ?> <small></small></h5>
                           
                        </div>
                        <div class="ibox-content">
                       
                   
                    
                            <?php
                            
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('action', $this->url('dashboard', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form); ?>


<?php foreach ( $form as $element ) :

if($element->getLabel()=='Picture'){ ?>

<div class="row">
                        <div class="col-sm-8 col-xs-12">
                            <div class="profile-pic">
                            <label for="file-upload" class="custom-file-upload">
                                 Change Picture
                                </label>
               <input type='file' name="picture"  class="form-control photo" id="inputFile">
                                <div class="form-photo">
                                <?php $avatar='/avatar/noavatar.jpg';
                                if(strpos($image,'data:image')!==false){ ?>
                    <img id="image-preview" src="<?php echo $image ?>" width="auto" height="100" alt="" />                        <?php }else{ ?>
        <img id="image-preview" src="<?php echo $this->basePath($avatar)?>" width="auto" height="100" alt="" />
                                <?php  }    ?> 
                                </div>
                             </div>
                             <div class="form-group">
                            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
                            
                            </div>
                        </div>
                  <span class="help-inline  error "><?php echo $this->formElementErrors($element) ?></span>
                        </div>
                    </div>
                     <div class="row">
                        <div class="col-sm-12">
                            <h4>Personal Information</h4>
                        </div>
                    </div>



<?php }else {?>

<div    class="form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">

        <label class=" col-sm-2 col-md-2 control-label"><?php echo $element->getLabel() ?></label>
        <div class="col-sm-6 col-md-4">
                <?php echo $this->formElement ( $element );
                    if ($this->formElementErrors ( $element ))
                ?>
    <span class="help-inline  error "><?php echo $this->formElementErrors($element) ?></span>
        </div>
    </div>
   
     
<?php }
endforeach;


echo $this->form()->closeTag();
?>

                              
                           
                         
                              
                               
                             
                           
                               
                        </div>
                    </div>
                </div>
</div>
<style>
span.help-inline ul li {
  color: red;
  list-style: none;
  
}
</style>
<script type="text/javascript">
          
          $('#country').on('change', function() {
     $("#countrycode").val($(this).val());
});
          
            function readURL(input) {
                if (input.files) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        $('#image-preview').attr('src', e.target.result);
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#inputFile").change(function() {
                readURL(this);
            });

        </script>