
<div>
<?php echo $this->partial('rnav'); ?>
<?php echo $this->partial('headnav'); ?>

<div id="page-wrapper" class="gray-bg">
    <!--top navigation-->
<!---->
<!---->
<!--    <h1>--><?php //echo $this->escapeHtml($title); ?><!--</h1>-->
<!--    --><?php
//    $form->setAttribute('action', $this->url('album', array('action' => 'add')));
//    $form->prepare();
//
//    echo $this->form()->openTag($form);
//    /*
//    echo $this->formHidden($form->get('id'));
//    echo $this->formRow($form->get('title'));
//    echo $this->formRow($form->get('artist'));
//    echo $this->formSubmit($form->get('submit'));
//    */
//    echo $this->formCollection($form);
//    echo $this->form()->closeTag();
//?>

    </div>


    <?php echo $this->partial('footer'); ?>


</div>
</div>