

    <?php echo $this->partial('rnav'); ?>
    <?php echo $this->partial('headnav'); ?>

    <div id="page-wrapper" class="gray-bg">
        <!--top navigation-->
        <?php echo $this->partial('headtitle'); ?>

        <?php echo $this->partial('profile'); ?>
        <?php echo $this->partial('mentorinfo'); ?>
        <?php echo $this->partial('wbsinfo'); ?>
        <div class="row">



        </div>


    </div>
    <?php echo $this->partial('footer'); ?>
