<?php echo $this->headLink()->prependStylesheet($this->basePath('/js/plugins/croppie/croppie.css')); ?>
<script src="<?php echo $this->basePath('/js/plugins/croppie/croppie.min.js')?>" ></script>
<style>
    .upload-msg {
        text-align: center;
        padding: 50px;
        font-size: 22px;
        color: #aaa;
        width: 260px;
        margin: 50px auto;
        border: 1px solid #aaa;
    }
</style>
<div class="row">
<div class="col-lg-12">
                    <div class="ibox float-e-margins">
                        <div class="ibox-title">
                            <h5><?php echo $this->escapeHtml(ucwords($title)); ?> <small></small></h5>
                           
                        </div>
                        <div class="ibox-content">
                       
                   
                    
                            <?php
                            
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form-horizontal');
$form->setAttribute('action', $this->url('dashboard', array('action' => 'profile')));
$form->prepare();
echo $this->form()->openTag($form); ?>




<?php 

foreach ( $form as $element ) :

 if($element->getName()=='submit'){
     $submitelement=$element;
 continue;
 }

if($element->getLabel()=='Picture'  ){ ?>

<div class="row">
                        <div class="col-sm-8 col-xs-12">



                         
                            <div class="profile-pic">

                                <label for="file-upload" class="custom-file-upload">
                                 Change Picture
                                </label>
               <input type='file' name="picture"  class="form-control photo" id="inputFile">
                               
                                 
                                <div class="form-photo">
                                    <div class="demo"></div>

                                 <?php $avatar='/avatar/noavatar.jpg'; 
                                 if(strlen($image)){
                                     $avatar=$image;
                                 }
                                 
                                 ?> 
                         <?php if(strpos($avatar,'data:image')!==false){ ?>
                    <img id="image-preview" src="<?php echo $avatar ?>" width="auto" height="100" alt="" />
                         <?php }else{ ?>
        <img id="image-preview" src="<?php echo $this->basePath($avatar)?>" width="auto" height="100" alt="" />

                             <script>
                                 $uploadCrop = $('#upload-demo').croppie({
                                     enableExif: true,
                                     viewport: {
                                         width: 200,
                                         height: 200,
                                         type: 'circle'
                                     },
                                     boundary: {
                                         width: 300,
                                         height: 300
                                     }
                                 });
                             </script>

                                <?php  }    ?>
                                </div>
                             </div>
                             <div class="form-group">
                            <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
                            
                            </div>
                        </div>
                  <span class="help-inline  error "><?php echo $this->formElementErrors($element) ?></span>
                        </div>
                    </div>
                     <div class="row">
                        <div class="col-sm-12">
                            <h4>Personal Information</h4>
                        </div>
                    </div>


<?php }else {?>

<div    class="form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">

        <label class=" col-sm-2 col-md-1 control-label"><?php echo $element->getLabel() ?></label>
        <div class="col-sm-4 col-md-4">
                <?php echo $this->formElement ( $element );
                    if ($this->formElementErrors ( $element ))
                ?>
    <span class="help-inline  error "><?php echo $this->formElementErrors($element) ?></span>
        </div>
    </div>
   
     
<?php }
endforeach; ?>
<div    class="form-group <?php if($this->formElementErrors($submitelement)) echo "has-error" ?>">
        <label class=" col-sm-2 col-md-1 control-label"><?php echo $submitelement->getLabel() ?></label>
        <div class="col-sm-4 col-md-4">
                <?php echo $this->formElement ( $submitelement );
                    if ($this->formElementErrors ( $submitelement ))
                ?>
    <span class="help-inline  error "><?php echo $this->formElementErrors($submitelement) ?></span>
        </div>
    </div>

<?php 
echo $this->form()->closeTag();
?>

                              
                           
                         
                              
                               
                             
                           
                               
                        </div>
                    </div>
                </div>
</div>
<style>
span.help-inline ul li {
  color: red;
  list-style: none;
  
}
</style>
<script type="text/javascript">



           
              $('#country').on('change', function() {
     $("#countrycode").val($(this).val());
});
          
            function readURL(input) {
                if (input.files) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        
                        
                        $('#image-preview').attr('src', e.target.result);
                    }


                    reader.readAsDataURL(input.files[0]);
                }
            }

            $("#inputFile").change(function() {
                readURL(this);
            });

        </script>




