<section id="contact" class="gray-section contact">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>Contact Us</h1>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.</p>
            </div>
        </div>
        <div class="row m-b-lg">
            <div class="col-lg-3 col-lg-offset-3">
                <address>
                    <strong><span class="navy">Deeplife.</span></strong><br>
                    64 The Chase, Mount Pleasant <br>
                    S954 Harare, Zimbabwe<br>
                    <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>
            </div>
            <div class="col-lg-4">
                <p class="text-color">
                    Aggressively evangelize, deeply build, urgently multiply to launch movements and spark the fire of revival, within <strong>PACT Area</strong>, and bring holistic transformation among unreached people groups.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">

                <button class="btn btn-primary " data-toggle="modal" data-target="#myModalNorm">
                    Contact&nbsp; <i class="fa fa-envelope-o"></i>
                </button>
                <style>
                    .modal-body .form-horizontal .col-sm-2,
                    .modal-body .form-horizontal .col-sm-10 {
                        width: 100%
                    }

                    .modal-body .form-horizontal .control-label {
                        text-align: left;
                    }
                    .modal-body .form-horizontal .col-sm-offset-2 {
                        margin-left: 15px;
                    }
                </style>
                <!-- Modal -->
                <div class="modal fade" id="myajaxforgot" tabindex="-1" role="dialog"
                     aria-labelledby="myajaxforgotLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <!-- Modal Header -->
                            <div class="modal-header">
                                <button type="button" class="close"
                                        data-dismiss="modal">
                                    <span aria-hidden="true">&times;</span>
                                    <span class="sr-only">Close</span>
                                </button>
                                <h4 class="modal-title" id="myajaxforgotLabel">
                                    Forgot password
                                </h4>
                                <p>Enter your email address and your password will be reset and emailed to you.
                                </p>
                            </div>

                            <!-- Modal Body -->
                            <div class="modal-body">

                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="alert alert-success" style="display: none;" >
                                            <strong>Thank you!</strong> Your password has been successfully sent.
                                        </div>
                                        <div class="alert alert-danger" style="display: none;" >
                                            <strong>Oops!</strong> Something went wrong. Please try again later.
                                        </div>

                                        <div class="ibox float-e-margins">

                                            <div class="ibox-content">
                                                <form method="get" class="form-horizontal">
                                                    <div class="form-group pemail"><label class="col-sm-2 control-label"> Email(required)</label>

                                                        <div class="col-sm-10"><input class="form-control" type="email" name="txtname" id="txtpemail" ></div>
                                                    </div>
                                                    <div class="hr-line-dashed"></div>
                                                    <div class="form-group phone"><label class="col-sm-2 control-label">Phone(required)</label>
                                                        <div class="col-sm-10"><input class="form-control" name="phone" id="phone" type="text">
                                                        </div>
                                                    </div>



                                                    <div class="hr-line-dashed"></div>
                                                    <button type="button" class="btn btn-primary" id="sendnewpassword" >
                                                        SEND NEW PASSWORD
                                                    </button>

                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <script>
                                    $( "#sendnewpassword" ).click(function() {
                                        $( "#sendnewpassword" ).html('SEND NEW PASSWORD <i class="fa fa-spinner fa-pulse fa-1x fa-fw margin-bottom"></i>').attr('disabled','disabled');
                                        $('.form-group').removeClass('has-error');
                                        var flag=1;
                                        var phone =$.trim($('#phone').val());
                                        var email =$.trim($('#txtpemail').val());

                                        if(phone==''){

                                            flag=0;
                                            $('.phone').addClass('has-error');
                                        }
                                        if(email==''){
                                            flag=0;
                                            $('.pemail').addClass('has-error');
                                        }else {
                                            var filter = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/;
                                            if (!filter.test(email)) {
                                                flag=0;
                                                $('.pemail').addClass('has-error');
                                            }
                                        }



                                        if(flag){

                                            $.ajax({
                                                url: "<?php echo $this->serverUrl('/ajaxforgot'); ?>",
                                                data: {phone: phone,email: email},
                                                type: 'post',
                                                success: function(output) {


                                                    if(output==1){
                                                        $('.alert-success').show();
                                                    }else{
                                                        $('.alert-danger').show();
                                                    }
                                                    $( "#sendnewpassword" ).html('SEND NEW PASSWORD').removeAttr('disabled');
                                                }
                                            });
                                        }else{
                                            $( "#sendnewpassword" ).html('SEND NEW PASSWORD').removeAttr('disabled');
                                        }

                                    });
                                </script>

                            </div>

                            <!-- Modal Footer -->

                        </div>
                    </div>
                </div>
                <div class="modal fade" id="myModalNorm" tabindex="-1" role="dialog"
                     aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <!-- Modal Header -->
                            <div class="modal-header">
                                <button type="button" class="close"
                                        data-dismiss="modal">
                                    <span aria-hidden="true">&times;</span>
                                    <span class="sr-only">Close</span>
                                </button>
                                <h4 class="modal-title" id="myModalLabel">
                                    Contact us
                                </h4>
                            </div>

                            <!-- Modal Body -->
                            <div class="modal-body">

                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="alert consuccess alert-success" style="display: none;" >
                                            <strong>Thank you!</strong> Your message has been successfully sent. We will contact you very soon!.
                                        </div>
                                        <div class="alert condanger alert-danger" style="display: none;" >
                                            <strong>Oops!</strong> Something went wrong. Please try again later.
                                        </div>

                                        <div class="ibox float-e-margins">

                                            <div class="ibox-content">
                                                <form method="get" class="form-horizontal">
                                                    <div class="form-group name"><label class="col-sm-2 control-label"> Your Name (required)</label>

                                                        <div class="col-sm-10"><input class="form-control" type="text" name="txtname" id="txtname" ></div>
                                                    </div>
                                                    <div class="hr-line-dashed"></div>
                                                    <div class="form-group email"><label class="col-sm-2 control-label">Your Email (required)</label>
                                                        <div class="col-sm-10"><input class="form-control" name="txtemail" id="txtemail" type="text">
                                                        </div>
                                                    </div>
                                                    <div class="hr-line-dashed"></div>
                                                    <div class="form-group message"><label class="col-sm-2 control-label">Your Message</label>
                                                        <div class="col-sm-10">
                                                            <textarea id="InputMessage" name="yourmessage" cols="40" rows="10" class="form-control" ></textarea>
                                                        </div>
                                                    </div>

                                                    <div class="hr-line-dashed"></div>
                                                    <button type="button" class="btn btn-primary" id="send" >
                                                        SEND
                                                    </button>

                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                <script>
                                    $( "#send" ).click(function() {
                                        $( "#send" ).html('SEND <i class="fa fa-spinner fa-pulse fa-1x fa-fw margin-bottom"></i>').attr('disabled','disabled');
                                        $('.form-group').removeClass('has-error');
                                        var flag=1;
                                        var name =$.trim($('#txtname').val());
                                        var email =$.trim($('#txtemail').val());


                                        var message =$.trim($('#InputMessage').val());
                                        if(name==''){

                                            flag=0;
                                            $('.name').addClass('has-error');
                                        }
                                        if(email==''){
                                            flag=0;
                                            $('.email').addClass('has-error');
                                        }else {
                                            var filter = /^[\w\-\.\+]+\@[a-zA-Z0-9\.\-]+\.[a-zA-z0-9]{2,4}$/;
                                            if (!filter.test(email)) {
                                                flag=0;
                                                $('.email').addClass('has-error');
                                            }
                                        }

                                        if(message==''){
                                            flag=0;
                                            $('.message').addClass('has-error');
                                        }

                                        if(flag){


                                            $.ajax({
                                                url: "<?php echo $this->serverUrl('/contactus'); ?>",
                                                data: {name: name,email: email,message: message},
                                                type: 'post',
                                                success: function(output) {

                                                    if(output){
                                                        $('.consuccess').show();
                                                    }else{
                                                        $('.condanger').show();
                                                    }
                                                    $( "#send" ).html('SEND').removeAttr('disabled');
                                                }
                                            });
                                        }else{
                                            $( "#send" ).html('SEND').removeAttr('disabled');
                                        }

                                    });
                                </script>

                            </div>

                            <!-- Modal Footer -->

                        </div>
                    </div>
                </div>
                <p class="m-t-sm">
                    Or follow us on social platform
                </p>
                <ul class="list-inline social-icon">
                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
                <p><strong>© 2015 Deeplife</strong><br> 64 The Chase, Mount Pleasant, 954 Harare, Zimbabwe</p>
            </div>
        </div>
    </div>
</section>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Scripts -->

<?php echo $this->inlineScript()->prependFile($this->basePath('js/pace.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/classie.js'))
    ->prependFile($this->basePath('js/cbpAnimatedHeader.js'))
    ->prependFile($this->basePath('js/wow.min.js'));
//->prependFile($this->basePath('js/inspinia.js'));

?>