 <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.11/css/jquery.dataTables.min.css">
  <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="widget style1 grey-bg">
                        <div class="row">
                            <div class="col-xs-4 text-center">
                                         <i class="fa-disciples"></i>
                            </div>
                            <div class="col-xs-8 text-right">
                                <span><strong><?php echo $this->translate('DISCIPLES TREE')?> </strong></span>
                                <h2 class="font-bold"> 
                                     <?php 
                                 echo sprintf("%02d",$disciples[0]->disciplescount);                                          ?>
                                
                                
                                </h2>
                           <span><?php echo $this->translate('Total Disciples')?></span>
                            </div>
                        </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="widget style1 yellow-bg">
                    <div class="row">
                        <div class="col-xs-4">
                          
                       <i class="fa-win"></i>
                        </div>
                        <div class="col-xs-8 text-right">
                            <span> <strong> <?php echo $this->translate('WIN')?></strong></span>
                            <h2 class="font-bold">
                            <?php  if(isset($stage[0]['win'])){echo sprintf("%02d",$stage[0]['win']);  }else { echo '00'; }   ?>
                           </h2>
                         <span> <?php echo $this->translate('Aggressively evangelize')?> </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="widget style1  blue-bg">
                    <div class="row">
                        <div class="col-xs-4">
                          <i class="fa-build"></i> 
                      
                        </div>
                        <div class="col-xs-8 text-right">
                            <span> <strong><?php echo $this->translate('BUILD')?> </strong></span>
                            <h2 class="font-bold">
                             <?php  if(isset($stage[0]['build'])){echo sprintf("%02d",$stage[0]['build']);  }else { echo '00'; }   ?>                            
                            </h2>
                         <span><?php echo $this->translate('Deeply build')?>  </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="widget style1 green-bg">
                    <div class="row">
                        <div class="col-xs-4">
                            <i class="fa-send"></i>
                        </div>
                        <div class="col-xs-8 text-right">
                            <span><strong> <?php echo $this->translate('SEND')?> </strong></span>
                            <h2 class="font-bold">
                                      <?php  if(isset($stage[0]['send'])){echo sprintf("%02d",$stage[0]['send']);  }else { echo '00'; }   ?> 
                                
                            </h2>
                        <span><?php echo $this->translate('Urgently multiply')?> </span> 
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
         

  <div class="row">
        <div class="col-lg-12">
        <div class="ibox float-e-margins">
        <div class="ibox-title">
            <h5>Admin Details</h5>
       </div>
        <div class="ibox-content">
            <div class="row">
                <div class="col-sm-1 m-b-xs">
          <a href="<?php echo $this->url('disciples', array('action'=>'add'));?>" class="btn  btn-sm btn-secondary">
          <?php echo $this->translate('Add Disciple')?></a>
         
</p>
                </div>
                <div class="col-offset-sm-8">
                   
                </div>
            </div>
          <div class="table-responsive">
                <table class="table table-striped  table-hover dataTables nowrap">
                    <thead>
                    <tr>
                    <th class="nodisplay" ></th>
                         <th><?php echo $this->translate('AVATAR')?></th>
                        <th><?php echo $this->translate('NAME')?> </th>
                        <th><?php echo $this->translate('EMAIL')?> </th>
                        <th><?php echo $this->translate('PHONE')?> </th>
                        <th><?php echo $this->translate('COUNTRY')?></th>
                         <th><?php echo $this->translate('BUILD STAGE')?></th>
                    <th><?php echo $this->translate('BUILD PERCENTAGE')?></th>
                      <th><?php echo $this->translate('ACTION')?></th>
                    </tr>
                    </thead>
                    <tbody>
                      <?php  foreach ($users as $user) : ?>
            <tr>  <td class="nodisplay" ></td>
                <td >
                <?php
              $avatar='/avatar/noavatar.jpg';
                 if( is_file('public'.$user->picture)) { 
               $avatar=$user->picture;
                }
                
                ?>
                
                <div style="
background-image: url('<?php echo $this->basePath($avatar);?>');
background-repeat: no-repeat;
width: 40px; 
height: 40px;
   background-size: cover; 
   background-position: center;
   border: solid 2px #fff;
" class="img-circle img-responsive"></div>	
<style>
.img-circle {
   border-radius: 50%;
}
.img-responsive {
   display: block;
   max-width: 100%;
   height: auto;
}    
tr td {
    vertical-align: middle;
}
</style>


</td>
                <td valign="middle"><?php echo $this->escapeHtml(ucwords($user->displayName));?></td>
                <td><?php echo $this->escapeHtml($user->email);?></td>
                <td><?php echo $this->escapeHtml($user->phone_no);?></td>
                <td><?php echo $this->escapeHtml(ucwords(strtolower($countries[$user->country])));
                ?></td>
                <td>
                 
                 <?php
                   $stage=strtolower($user->stage);
                   $percentage='0%';
                   $class='';
                  switch($stage){
                      
                       case 'build':
                      $class='blue-bg ';
                      $percentage='<div class=" font-bold text-blue">60% <i class="fa fa-level-up"></i></div>';
                      break;
                       case 'win':
                      $class='yellow-bg';
                      $percentage='<div class=" font-bold text-yellow">25%<i class="fa fa-level-up"></i></div>';
                      break;
                   case 'send':
                      $class='green-bg';
                      $percentage='<div class=" font-bold text-green">100%<i class="fa fa-level-up"></i></div>';
                      break;
                  
                  case 'added':
                  default:    
                      $class='btn-danger';
                      $percentage='<div class=" font-bold text-danger">0%<i class="fa fa-level-up"></i></div>';
                      break;
                     
                  
                  }
                  
                   ?> 
                 
                  <a  href="<?php echo $this->url('movement', array('action'=>'question', 'id' => $user->id));?>" class="fbox tips btn btn-xs <?php echo $class ?> "  >
                  <?php  echo $this->escapeHtml($user->stage==''?$this->translate('ADDED'):$this->translate(strtoupper($user->stage)));  ?></a> 
              
               </td>
               <td><?php echo $percentage; ?> </td>
              <td>
              <span class="action" >
<a href="<?php echo $this->url('disciples', array('action'=>'edit','id' => $user->id));?>" class="tips" title="Edit"><i class="fa fa-edit"></i> </a>
   <span>&#x7C;</span>
       <a href="<?php echo $this->url('disciples', array('action'=>'delete','id' => $user->id));?>" onclick="return confirm('<?php echo $this->translate('Are you sure you want to delete this item?')?>');" class="tips" title="Delete"> <i class="fa fa-trash-o"></i></a>
   	</span >
               </td>
            </tr>
        <?php endforeach; ?>
                   
                    </tbody>
                </table>
           
        </div>
            </div>
        </div>
        </div>
        </div>

      
    <?php echo $this->headScript()
 ->prependFile($this->basePath('js/plugins/dataTables/jquery.dataTables.min.js')) ;
 ?>

 <script>
        $(document).ready(function() {
            $('.dataTables').dataTable({
     	"order": [[ 0, "asc" ]],
       "columnDefs": [ {"targets": 1,"orderable": false},{"targets": 8,"orderable": false} ],

            });
             
             });
 </script> 