 <?php echo $this->headLink()->prependStylesheet($this->basePath('/css/build.css')); ?> 
 <?php echo $this->headLink()->prependStylesheet($this->basePath('js/plugins/multipleselect/bootstrap-multiselect.css')); ?> 
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Manage Roles</h5>
            </div>
            <div class="ibox-content">
   <form method="post" name="SamUser" class="" action=""  id="SamUser">
                    <div class="row">
                        <div class="form-group col-sm-4">
                            <label for="usr">Select Role </label>
                            <?php  $role=array( 1 => 'User',4 => 'Countryadmin') ; 
                           if($myroleid==2){
                               $role[2] = 'Superadmin';
                               $role[3] = 'Areaadmin';
                              }
                            ?>
                          <select id="role" class="form-control m-b" name="role">
                           <?php foreach($role as $key => $val){ 
                             $selectVal='';
                            if($roleid == $key){
                                  $selectVal = 'selected';
                                 $showval=$key;
                            }
                            
                            echo "<option ". $selectVal ."  value='".$key."' >".$val."</option>";
                              }
                             ?>     
                               </select>
                        </div>
                    </div>
                   
                    <div class="row jsselect " id="countrydiv"  <?php if($showval==4) { echo "style=display:block;" ; } else {  echo "style=display:none;"; } ?> >
                        <div class="form-group col-sm-4">
                            <label for="usr">Select Countries</label>
                           
                            <select id="country" class="form-control m-b" name="country" >
                           <?php foreach($countries as $key => $val){ 
                             $selectVal='';
                            if($roleCountry == $key){
                              $selectVal = 'selected';
                            }
                           
                           echo "<option ". $selectVal ."  value='".$key."' >".$val."</option>";
                              }
                             ?>     
                               </select>
                                                   </div>
                    </div>
              
               
                <div class="row jsselect"  id="areagroupsdiv"  <?php if($showval==3) { echo "style=display:block;"; }else {  echo "style=display:none;"; }?> >
                        <div class="form-group col-sm-4">
                        
                        <?php $roleGroups=json_decode($roleGroups);?>
                          <label for="usr">Select Area Groups</label>
                           <select id="areagroups" class="form-control m-b" name="areagroups[]" multiple="multiple" >
                           <?php foreach($areagroups as $key => $val){ 
                           $selectVal='';
                            if(in_array($key,$roleGroups)){
                              $selectVal = 'selected';
                            }
                           
                           echo "<option ". $selectVal ."  value='".$key."' >".$val."</option>";
                           
                              }
                             ?>     
                               </select>
                        </div>
                    </div>
                
                    <div class="row">
                        <div class="form-group col-sm-4 text-right">
                            <input type="submit" name="submit" id="submitbutton" class="btn btn-primary" value="Save">
                           
                        </div>
                    </div>
            </div>
            </form>
        </div>
    </div>
</div>

 
 <script src="<?php echo $this->basePath('js/plugins/multipleselect/bootstrap-multiselect.js')?>"></script>
 
<script>
   
    $( "#role" ).change(function() {
      var roleVal=$(this).val();
    $('.jsselect').hide();
      if(roleVal==3 ){
         $('#areagroupsdiv').show();
      }else if(roleVal==4){
         $('#countrydiv').show();
      }


});
    
</script>

 <script type="text/javascript">
    $(document).ready(function() {
     
           $('#areagroups').multiselect({
          // onChange: function(option, checked, select) {
                         //  var country = $('#areagroups option:selected');  
             //alert ( $('#role').val());
           //}
        
        
        });
           });
</script>
<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Alert</h4>
        </div>
        <div class="modal-body">
          <p>Please select only three countries.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
    <div class="modal-backdrop fade in inside"></div>
  </div>