
<!DOCTYPE html>
<html>
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>
<head>
    <?php echo $this->form()->openTag($form) ?>
    <title>DeepLife</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Add Your favicon here -->
    <!--<link rel="icon" href="img/favicon.ico">-->



    <!-- Bootstrap core CSS -->

    <link href="../css/bootstrap.min.css" rel="stylesheet">

    <!-- Animation CSS -->
    <link href="../css/animate.min.css" rel="stylesheet">

    <link href="../font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>

    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="../css/style.css" rel="stylesheet">

</head>

<body class="." id="page-top">

<div class="navbar-wrapper">

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container" >
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="background-color: #03b2d4; font-size: 200%;" href="#">DEEPlife</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a class="page-scroll" href="#page-top">Home</a></li>
                    <li><a class="page-scroll" href="#features">Sign in</a></li>
                    <!--<li><a class="page-scroll" href="#team">Signup</a></li>-->
                    <li><a class="page-scroll" href="#testimonials">Features</a></li>
                    <li><a class="page-scroll" href="#pricing">About</a></li>
                    <li><a class="page-scroll" href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<div id="inSlider" class="carousel slide carousel-fade" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#inSlider" data-slide-to="0" class="active"></li>
        <li data-target="#inSlider" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div class="container">
                <div class="carousel-caption">
                    <h1>Everyone<br/>
                        desciple 5.<br/>
                        <br/>
                    </h1>
                    <p>Aggressively evangelize, deeply build, urgently multiply</p>
                    <p>
                        <a class="btn btn-lg btn-primary" href="#pricing" role="button" style="background-color:#03b2d4 ;">Learn More</a>
                        <!--<a class="caption-link" href="#" role="button">Inspinia Theme</a>-->
                    </p>
                </div>
                <!--<div class="carousel-image wow zoomIn">-->
                <!--<img src="img/laptop.png" alt="laptop"/>-->
                <!--</div>-->
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back one"></div>

        </div>
        <div class="item">
            <div class="container">
                <div class="carousel-caption blank">
                    <h1>“Don’t be afraid; <br/> from now on you will be catching men”</h1>

                    <p>Launch deep in the see. </p>
                    <p><a class="btn btn-lg btn-primary" href="#pricing" role="button">Learn more</a></p>
                </div>
            </div>
            <!-- Set background for slide in css -->
            <div class="header-back two"></div>
        </div>
    </div>
    <a class="left carousel-control" href="#inSlider" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#inSlider" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<section id="features" class="container services">
    <div class="row">
        <div class="col-sm-6">
            <br/><br/><br/>
            <div class="col-sm-8 col-sm-offset-2">
                <img  src="../img/logooo.png"/>
            </div>
            <div class="col-sm-8 col-sm-offset-2" style="text-align: center;">
                <h5>Everyone disciple five. </h5>
            </div>

        </div>


        <div class="col-sm-6">
            <h2 style="text-align: left;">Signin</h2>
            <h4>Log in back to your Account</h4>
            <formgroup style="align-content: center;">
                <div class="col-sm-8">
                    <div class="row zeroMargin margin-top-20">
                        <input class="form-control" placeholder="Enter email adress">
                    </div><br/>
                    <div class="row zeroMargin margin-top-20">
                        <input class="form-control" placeholder="enter password">
                    </div>



                    <br/>
                    <!--this is the sign up button-->
                    <div class="row zeroMargin margin-top-20">

                        <button type="button" class="btn btn-info col-md-12">
                            <strong>Sign in</strong>
                        </button><br/><br/>
                        <h4>
                            Don't have an account yet?
                        </h4>
                        <button type="button" class="btn btn-info col-md-12">
                            <strong>Sign UP</strong>
                        </button>
                    </div>
                </div>
            </formgroup>
            <!--<p><a class="navy-link" href="#" role="button">Details &raquo;</a></p>-->
        </div>
    </div>

</section>
<section  class="container features">
    <div class="row">
        <div class="col-lg-12 text-center">
            <div class="navy-line"></div>
            <h1>Ultimate growth<br/> <span class="navy"> with high class features</span> </h1>
            <p>Reach the globe with the spirit of God's Word. </p>
        </div>
    </div>
    <section id="testimonials">
        <div class="row">
            <div class="col-md-3 text-center wow fadeInLeft">
                <div>
                    <span class="glyphicon glyphicon-user" style="font-size: 250%; Color:deepskyblue;"></span>
                    <h2>Win</h2>
                    <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus.</p>
                </div>
                <div class="m-t-lg">
                    <span class="glyphicon glyphicon-road" style="font-size: 250%; Color:deepskyblue;"></span>
                    <h2>Build</h2>
                    <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus.</p>
                </div>
            </div>
            <div class="col-md-4 col-sm-offset-1 text-center  wow zoomIn">
                <img src="../img/logooo.png" alt="dashboard" class="img-responsive">
            </div>
            <div class="col-md-3 text-center wow fadeInRight">
                <div>
                    <span class="glyphicon glyphicon-send" style="font-size: 250%; Color:deepskyblue;"></span>
                    <h2>Send</h2>
                    <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus.</p>
                </div>
                <div class="m-t-lg">
                    <span class="glyphicon glyphicon-cloud" style="font-size: 250%; Color:deepskyblue;"></span>
                    <h2>Track</h2>
                    <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus.</p>
                </div>
            </div>
        </div>
        <section id="pricing"></section>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>About Deep life</h1>
                <!--<p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. </p>-->
            </div>
            <div class="row features-block">
                <div class="col-lg-6 features-text wow fadeInLeft">
                    <!--<small>INSPINIA</small>-->
                    <h2>Launch out to the deep. </h2>
                    <p>It is not a strange thing to hear the statement, “African
                        Christianity is a mile wide but an inch deep.” This is to say that
                        African church growth focuses mostly on quantity than quality.
                        There could be lots of energy, time and resources put into
                        expansion, coverage, and exposure through evangelism when
                        compared to helping someone to truly follow Christ, get grounded in
                        the faith and take deep root in the word of God and lead a transformed,
                        authentic and Christ-like life style in private and public arenas.
                        As an organization, Campus Crusade for Christ seeks to produce true followers of
                        Jesus. It received its mandate from our Lord and savior Jesus Christ to “go…and
                        make disciples of all nations” (Matthew 28:19). In collaboration with the body of Christ,
                        the ministry desires to contribute meaningfully in becoming a “salt and light” to the
                        problem for the glory of God. It is out of such genuine desire that the vision of “Deep
                        Life” has been born. Our goal is to train and equip 100, 000 leaders who shall be
                        planting and building 100,000 churches on cities, villages, campuses,
                        student population centers, market places, and online networks.
                        This vision has 3 phases of implementation. Feb 10 – 31 Dec 2014 shall
                        be a time of prayer and preparation. Jan 1 – 31 Dec 2015 will be a
                        year of mobilization and training. Jan 1- Oct 10/2016 shall be a
                        time of full implementation and accelerated actions across
                        the 24 countries of the Southern and Eastern Africa in 240
                        locations.</p>
                    <!--<a href="" class="btn btn-primary">Learn more</a>-->
                </div>
                <div class="col-lg-6 text-right wow fadeInRight">
                    <img src="../img/dash.jpg" alt="dashboard" class="img-responsive pull-right">
                </div>
            </div>
        </div>

    </section>
</section>



<div class="loginColumns animated fadeInDown">
    <div class="row">

        <div class="col-md-6">
            <div class="ibox-content">
                <form class="m-t" role="form" action="index.html">
            <?php echo $this->form()->openTag($form) ?>
            <dl class="zend_form">
                <div class="form-group">
                    <?php echo $this->formElementErrors($form->get('identity')) ?>
                    <input type="email" class="form-control" placeholder="email" required="" <?php echo $this->formInput($form->get('identity')) ?>
                </div>


<!--                <dt>--><?php //echo $this->formLabel($form->get('identity')) ?><!--</dt>-->
<!--                <dd>--><?php //echo $this->formInput($form->get('identity')) ?><!--</dd>-->
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" required="" <?php echo $this->formInput($form->get('credential')) ?>
                </div>
<!--                <dt><label>--><?php //echo 'Password'; ?><!--</label></dt>-->
<!--                <dd>--><?php //echo $this->formInput($form->get('credential')) ?><!--</dd>-->

                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo 'Sign In'; ?>" />
                <?php endif ?>

<!--                <dd>--><?php //echo $this->formButton($form->get('submit')) ?><!--</dd>-->
            </dl>

            <?php echo $this->form()->closeTag() ?>



                    <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                    <a href="<?php echo $this->url('zfcuser/changepassword') ?>">
                        <small>Forgot password?</small>
                    </a>

                    <p class="text-muted text-center">
                        <small>Do not have an account?</small>
                    </p>
                    <a class="btn btn-sm btn-white btn-block" href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>" <?php if ($this->enableRegistration) : ?>
                        <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Create an account</a>
                <?php endif; ?>
                </form>
<!--                --><?php //if ($this->enableRegistration) : ?>
<!--                    Not registered? <a href="--><?php //echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?><!--">Sign up!</a>-->
<!--                --><?php //endif; ?>
                <p class="m-t">
                    <small>Deep-life CCCSEA &copy; 2015</small>
                </p>
            </div>
        </div>
    </div>
    <hr/>

</div>
<section id="contact" class="gray-section contact">
    <div class="container">
        <div class="row m-b-lg">
            <div class="col-lg-12 text-center">
                <div class="navy-line"></div>
                <h1>Contact Us</h1>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod.</p>
            </div>
        </div>
        <div class="row m-b-lg">
            <div class="col-lg-3 col-lg-offset-3">
                <address>
                    <strong><span class="navy">Deeplife.</span></strong><br/>
                    64 The Chase, Mount Pleasant <br/>
                    S954 Harare, Zimbabwe<br/>
                    <abbr title="Phone">P:</abbr> (123) 456-7890
                </address>
            </div>
            <div class="col-lg-4">
                <p class="text-color">
                    Aggressively evangelize, deeply build, urgently multiply to launch movements and spark the fire of revival, within Southern & Eastern Africa, and bring holistic transformation among unreached people groups.
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <a href="mailto:test@email.com" class="btn btn-primary">Send us mail</a>
                <p class="m-t-sm">
                    Or follow us on social platform
                </p>
                <ul class="list-inline social-icon">
                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center m-t-lg m-b-lg">
                <p><strong>&copy; 2015 Deeplife</strong><br/> 64 The Chase, Mount Pleasant, 954 Harare, Zimbabwe</p>
            </div>
        </div>
    </div>
</section>
<script src="js/jquery-2.1.1.js"></script>
<script src="js/pace.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/classie.js"></script>
<script src="js/cbpAnimatedHeader.js"></script>
<script src="js/wow.min.js"></script>
<script src="js/inspinia.js"></script>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>

</body>

</html>
