
<!DOCTYPE html>
<html>
<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>
<head>
    <?php echo $this->form()->openTag($form) ?>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Deep Life Login</title>

    <link href="../css/bootstrap.min.css" rel="stylesheet">
    <link href="../font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="../css/animate.css" rel="stylesheet">
    <link href="../css/style.css" rel="stylesheet">

</head>

<body class="gray-bg">

<div class="loginColumns animated fadeInDown">
    <div class="row">

        <div class="col-md-6">


            <div class="m-b-sm">
                <img alt="image"  align="center"   width= "250px"height="101px"  src="../img/logo.png">
            </div>
            <h1 class="font-bold">Welcome to Deep-Life</h1>

        </div>
        <div class="col-md-6">
            <div class="ibox-content">
                <form class="m-t" role="form" action="index.html">
            <?php echo $this->form()->openTag($form) ?>
            <dl class="zend_form">
                <div class="form-group">
                    <?php echo $this->formElementErrors($form->get('identity')) ?>
                    <input type="email" class="form-control" placeholder="email" required="" <?php echo $this->formInput($form->get('identity')) ?>
                </div>


<!--                <dt>--><?php //echo $this->formLabel($form->get('identity')) ?><!--</dt>-->
<!--                <dd>--><?php //echo $this->formInput($form->get('identity')) ?><!--</dd>-->
                <div class="form-group">
                    <input type="password" class="form-control" placeholder="Password" required="" <?php echo $this->formInput($form->get('credential')) ?>
                </div>
<!--                <dt><label>--><?php //echo 'Password'; ?><!--</label></dt>-->
<!--                <dd>--><?php //echo $this->formInput($form->get('credential')) ?><!--</dd>-->

                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo 'Sign In'; ?>" />
                <?php endif ?>

<!--                <dd>--><?php //echo $this->formButton($form->get('submit')) ?><!--</dd>-->
            </dl>

            <?php echo $this->form()->closeTag() ?>



                    <button type="submit" class="btn btn-primary block full-width m-b">Login</button>

                    <a href="<?php echo $this->url('zfcuser/changepassword') ?>">
                        <small>Forgot password?</small>
                    </a>

                    <p class="text-muted text-center">
                        <small>Do not have an account?</small>
                    </p>
                    <a class="btn btn-sm btn-white btn-block" href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>" <?php if ($this->enableRegistration) : ?>
                        <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Create an account</a>
                <?php endif; ?>
                </form>
<!--                --><?php //if ($this->enableRegistration) : ?>
<!--                    Not registered? <a href="--><?php //echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?><!--">Sign up!</a>-->
<!--                --><?php //endif; ?>
                <p class="m-t">
                    <small>Deep-life CCCSEA &copy; 2015</small>
                </p>
            </div>
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-6">
            Cru SEA
        </div>
        <div class="col-md-6 text-right">
            <small>© 2015</small>
        </div>
    </div>
</div>

</body>

</html>
