<body class="white-bg">
<div  class="-align-center middle-box animated fadeInDown ">

    <div class=" col-sm-12 " style="vertical-align: 500px;">

        <div style="vertical-align: 50%" class="ibox-content  text-foo white-bg ">
      <img class="middle-box col-md-12" src="<?php echo $this->basePath('img/Splashlogo_hdpi.png')?>">
            <h2 style="color: white">Sign In</h2>
            <h4 style="color: white">Log in with Email  or phone number </h4>
            <?php if(strlen($flashMessages)):  ?>
            <span class="help-inline " ><ul>    <li><?php echo $flashMessages; ?></li> </ul>
                <?php endif; ?>
                <?php
                $form = $this->loginForm;
                $form->prepare();
                $form->setAttribute('action', $this->url('zfcuser/login'));
                $form->setAttribute('method', 'post');
                $form->setAttribute('class', ' ');
                ?>
                <?php echo $this->form()->openTag($form) ?>
                <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">
                         <?php echo $this->formElement ( $form->get('identity')->setAttribute('class', 'form-control') );
                         if ($this->formElementErrors ( $form->get('identity') ))
                         ?>
                    <span class="help-inline  error "><?php echo $this->formElementErrors($form->get('identity')) ?></span>

                        </div>
                        <div  class=" form-group">
                           <?php echo $this->formElement ( $form->get('credential')->setAttribute('class', 'form-control') );
                           if ($this->formElementErrors ( $form->get('credential') ))
                           ?>
                            <span class="help-inline  error "><?php echo $this->formElementErrors($form->get('credential')) ?></span>


                        </div>
                        <button type="submit" class="btn btn-primary block btn btn-info  full-width m-b">Login</button>

                <?php if ($this->enableRegistration) : ?>
                    <a style="color: #f9c123" data-toggle="modal" data-target="#myajaxforgot" >Forgot password!</a><h6 style="color: white">Not registered ? </h6>
                    <a style="color: #f9c123" href="<?php echo $this->url('signup') ?>">Sign up!</a>
                <?php endif; ?>

                <?php echo $this->form()->closeTag() ?>


        </div>
    </div>
</body>




<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Deeplife| Register</title>

    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/animate.min.css'))
        ->prependStylesheet($this->basePath('css/style.min.css'))
        ->prependStylesheet($this->basePath('css/login_reg.css'))
        ->prependStylesheet($this->basePath('font-awesome/css/font-awesome.min.css'))
    ?>

</head>

<body class="white-bg">




</body>

</html>
<?php echo $this->inlineScript()
    ->prependFile($this->basePath('js/pace.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/classie.js'))
    ->prependFile($this->basePath('js/jquery-2.1.1.js'))
    ->prependFile($this->basePath('js/plugins/iCheck/icheck.min.js'))
    ->prependFile($this->basePath('js/cbpAnimatedHeader.js'))
    ->prependFile($this->basePath('js/wow.min.js'))
->prependFile($this->basePath('js/inspinia.js'));

?>
<script>
    $(document).ready(function(){
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green',
        });
    });
</script>
