
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DeepLife||Register</title>
        <link href="../css/bootstrap.min.css" rel="stylesheet">
        <link href="../font-awesome/css/font-awesome.css" rel="stylesheet">
        <link href="../css/plugins/iCheck/custom.css" rel="stylesheet">
        <link href="../css/animate.css" rel="stylesheet">
        <link href="../css/style.css" rel="stylesheet">
</head>
<body class="gray-bg" style="background-color:whitesmoke"></body>
<div class="row">
    <div class="middle-box text-center loginscreen   animated fadeInUp" width="500px">
        <div>
        <!--<h1 class="logo-name">IN+</h1>-->
        </div>
        <div class="m-b-sm">
            <img alt="image"  align="center" width= "250px"height="101px"  src="../img/logo.png">
        </div>
        <h3></h3>
        <!--<p>Create account to see it in action.</p>-->
        <div class="col-sm-12">
<!--            --><?php //echo $this->form()->openTag($form) ?>
<!---->
<!--            <dl class="zend_form">-->
                <?php echo $this->form()->openTag($form) ?>
                <dl class="zend_form">
                    <?php foreach ($form as $element): ?>
                        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
                            <dt><?php echo $this->formLabel($element) ?></dt>
                        <?php endif ?>
                        <?php if ($element instanceof Zend\Form\Element\Button): ?>
                            <dd><?php echo $this->formButton($element) ?></dd>
                        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
                        <?php else: ?>
                            <dd><?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
                        <?php endif ?>
                    <?php endforeach ?>
                </dl>
                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php endif ?>
                <?php echo $this->form()->closeTag() ?>
<!--            <div class="form-group">-->
<!--                <input type="text" class="form-control" placeholder="First Name" required="">-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <input type="text" class="form-control" placeholder="Middle Name" required="">-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <input type="text" class="form-control" placeholder="Last Name" required="">-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <input type='tel' class="form-control" pattern='[\+]\d{2}[\(]\d{2}[\)]\d{4}[\-]\d{4}' title='Phone Number (Format: +99(99)9999-9999)'-->
<!--                       placeholder="mentor phone number">-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <input type='tel' class="form-control" pattern='[\+]\d{2}[\(]\d{2}[\)]\d{4}[\-]\d{4}' title='Phone Number (Format: +99(99)9999-9999)'-->
<!--                       placeholder=" phone number">-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <input type="email" class="form-control" placeholder="Email" required="">-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <input type="password" class="form-control" placeholder="Password" required="">-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <input type="password" class="form-control" placeholder=" comfirm Password" required="">-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <select class="form-control">-->
<!--                    <option>Select Sex</option>-->
<!--                    <option>female</option>-->
<!--                    <option>male</option>-->
<!--                </select>-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <select class="form-control">-->
<!--                    <option>Select Country</option>-->
<!--                    <option>Ethiopia</option>-->
<!--                    <option>Ertria</option>-->
<!--                    <option>Kenya</option>-->
<!--                    <option>Djibuti</option>-->
<!--                    <option>Sudan</option>-->
<!--                    <option>somalia</option>-->
<!--                    <option>Nigeria</option>-->
<!--                    <option>Zimbabwe</option>-->
<!--                    <option>Ruwanda</option>-->
<!--                </select>-->
<!--            </div>-->
<!--            <div class="form-group">-->
<!--                <div class="checkbox i-checks"><label> <input type="checkbox"><i></i> Agree the terms and policy </label></div>-->
<!--            </div>-->
<!--            <button type="submit" class="btn btn-primary block full-width m-b">Register</button>-->

            <p class="text-muted text-center"><small>Already have an account?</small></p>
            <a class="btn btn-sm btn-white btn-block" href="<?php echo $this->url('zfcuser/login') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Login</a>
            <p class="m-t"> <small>deep-Life &copy; 2014</small> </p>
        </div>
    </div>
</div>
</div>
</div>
<!-- Mainly scripts -->
<script src="/public/js/jquery/jquery-2.1.1.min.js"></script>
<script src="/public/js/bootstrap/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="/public/js/plugins/iCheck/icheck.min.js"></script>
<script>

    $(document).ready(function(){
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });
    });
</script>
</body</body>
</html>
</html>
<!--<h1>Register</h1>-->
<!---->


