
<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<head>
    <title>Register</title>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<!-- Add Your favicon here -->
<!--<link rel="icon" href="img/favicon.ico">-->


<!-- Bootstrap core CSS -->
<link href="../css/bootstrap.min.css" rel="stylesheet">

<!-- Animation CSS -->
<link href="../css/animate.min.css" rel="stylesheet">

<link href="../font-awesome/css/font-awesome.min.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Custom styles for this template -->
<link href="../css/style.css" rel="stylesheet">
</head>
<body class="gray-bg" style="background-color:whitesmoke"></body>
<div class="navbar-wrapper">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="landing.html">Deeplife</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <!--<li><a class="page-scroll" href="#page-top">Home</a></li>-->
                    <!--<li><a class="page-scroll" href="#features">Sign in</a></li>-->
                    <!--&lt;!&ndash;<li><a class="page-scroll" href="#team">Signup</a></li>&ndash;&gt;-->
                    <!--<li><a class="page-scroll" href="#testimonials">Features</a></li>-->
                    <!--<li><a class="page-scroll" href="#pricing">About</a></li>-->
                    <!--<li><a class="page-scroll" href="#contact">Contact</a></li>-->
                </ul>
            </div>
        </div>
    </nav>
</div>
<div class="row">
    <div>
        <div class="col-sm-4 col-sm-offset-4">
            <br/><br/><br/>
            <div class="col-sm-8 col-sm-offset-2">
                <img  src="../img/logooo.png"/>
            </div>
            <div class="col-sm-8 col-sm-offset-2" style="text-align: center;">
                <h5>Everyone disciple five. </h5>
            </div>

        </div>
    </div>
</div>
<!---->
<!--<div class="col-sm-4 col-sm-offset-4">-->
<!---->
<!--    <formgroup class="col-sm-10 col-sm-offset-1" style="background-color:white; border: 1px solid gray; border-radius: 5px;">-->
<!--        <h4 style="text-align: center;">Just few  details...</h4>-->
<!--        <div class="col-sm-12 margin-top-5">-->
<!--            <div class="row zeroMargin margin-top-20">-->
<!--                <input class="form-control" placeholder="Full Name">-->
<!--            </div><br/>-->
<!--            <div class="row zeroMargin margin-top-20">-->
<!--                <input class="form-control" placeholder="Enter email address">-->
<!--            </div><br/>-->
<!--            <div class="row zeroMargin margin-top-20">-->
<!--                <input class="form-control" placeholder="Create password">-->
<!--            </div>-->
<!--            <p>I am:</p>-->
<!--            <div class="col-md-4">-->
<!--                <input type="radio" name="gender" class="col-md-5" id="male">-->
<!--                <label for="male" class="col-md-7 dark" style="color: black;">Male</label>-->
<!--            </div>-->
<!---->
<!--            <div class="col-md-4 col-md-offset-1">-->
<!--                <input type="radio" name="gender" class="col-md-5" id="female">-->
<!--                <label for="female" class="col-md-7 dark" style="color:black;">Female</label>-->
<!--            </div>-->
<!---->
<!--        </div>-->
<!--        <br/><br/>-->
<!---->
<!----
<!--        <div class="col-sm-5">-->
<!--            <select class="form-control">-->
<!--                <option>Country</option>-->
<!--                <option>Kenya</option>-->
<!--                <option>Tanzania</option>-->
<!--                <option>South Africa</option>-->
<!--                <option>Malawi</option>-->
<!--                <option>Ethiopia</option>-->
<!--            </select>-->
<!---->
<!---->
<!--        </div>-->
<!---->
<!--        <div class="col-sm-7">-->
<!--            <input class="form-control" placeholder="Enter Phone number">-->
<!--        </div>-->
<!---->
<!---->
<!--        <br/><br/><br/>-->
<!--        <label for="InputFile">Profile picture</label><br/>-->
<!--        <input type="file" id="InputFile" placeholder="Upload">-->
<!--        <p class="help-block"></p><br/>-->
<!--        <div class="row zeroMargin margin-top-20">-->
<!---->
<!--            <button type="button" class="btn btn-info col-md-12">-->
<!--                <strong>Sign Up</strong>-->
<!--            </button>-->
<!---->
<!--        </div>-->
<!--    </formgroup>-->
<div class="row" style="margin-top:3%;">


    </div>
</div>


<div class="row">
    <div class="middle-box text-center loginscreen   animated fadeInUp" width="500px">

        <div class="col-sm-12">
<!--            --><?php //echo $this->form()->openTag($form) ?>
<!---->
            <dl class="zend_form">
                <?php echo $this->form()->openTag($form) ?>
                <dl class="zend_form">
                    <div class="col-sm-18">
                    <?php foreach ($form as $element): ?>
                        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
                            <dt><?php echo $this->formLabel($element) ?></dt>
                        <?php endif ?>
                        <?php if ($element instanceof Zend\Form\Element\Button): ?>
                            <dd><?php echo $this->formButton($element) ?></dd>
                        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
                            <dd><?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?></dd>
                        <?php else: ?>
                            <dd> <input type="password" class="form-control" placeholder="Password" required="" <?php echo $this->formInput($element) . $this->formElementErrors($element) ?></dd>
                        <?php endif ?>
                    <?php endforeach ?>
                </dl>
                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php endif ?>
                <?php echo $this->form()->closeTag() ?>
            <p class="text-muted text-center"><small>Already have an account?</small></p>
            <a class="btn btn-sm btn-white btn-block" href="<?php echo $this->url('zfcuser/login') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Login</a>
            <a class="btn btn-sm btn-white btn-block" href="index.phtml">rere</a>
            <p class="m-t"> <small>deep-Life &copy; 2014</small> </p>
        </div>
    </div>
</div>
</div>
</div>
<!-- Mainly scripts -->
<script src="/public/js/jquery/jquery-2.1.1.min.js"></script>
<script src="/public/js/bootstrap/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="/public/js/plugins/iCheck/icheck.min.js"></script>
<script>

    $(document).ready(function(){
        $('.i-checks').iCheck({
            checkboxClass: 'icheckbox_square-green',
            radioClass: 'iradio_square-green'
        });
    });
    <script src="js/jquery-2.1.1.js"></script>
<script src="../js/pace.min.js"></script>
<script src="../js/bootstrap.min.js"></script>
</script>
</html>


