<?php
if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}

if (!$this->enableRegistration) {
    print "Registration is disabled";
    return;
}
$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');

?>



<section id="sign-in" class="container services">
    <div class="row">
        <div class="col-sm-6">
            <br/><br/><br/>
            <div class="col-sm-8 col-sm-offset-2">
                <img  src="<?php echo $this->basePath('/img/logooo.png');?>"/>
            </div>
        </div>
        <div class="col-sm-12">
                <?php echo $this->form()->openTag($form) ?>
                <div>
                    <?php foreach ($form as $element): ?>

<div    class="form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">
        <label class=" col-sm-2 control-label"><?php echo $element->getLabel() ?></label>
        <div class="col-sm-10">
                <?php echo $this->formElement ( $element );
                    if ($this->formElementErrors ( $element ))
                ?>
            <span class="help-inline   "><?php echo $this->formElementErrors($element) ?></span>
        </div>
    </div>
      <div class="hr-line-dashed"></div>


                    <?php endforeach ?>



                <?php if ($this->redirect): ?>
                    <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
                <?php endif ?>
                <?php echo $this->form()->closeTag() ?>
                    <p class="text-muted "><h1>Already have an account?</h1></p>
                    <a class="btn btn-sm btn-white btn-block" href="<?php echo $this->url('zfcuser/login') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Login</a>
                 
    </div>

    </div>
</div>

</section>

<div class="loginColumns animated fadeInDown">
    <div class="row">

        <div class="col-md-6">
            <div class="ibox-content">
<!--                <form class="m-t" role="form" action="index.html">-->
<!--            --><?php //echo $this->form()->openTag($form) ?>
<!--            <dl class="zend_form">-->
<!--                <div class="form-group">-->
<!--                    --><?php //echo $this->formElementErrors($form->get('identity')) ?>
<!--                    <input type="email" class="form-control" placeholder="email" required="" --><?php //echo $this->formInput($form->get('identity')) ?>
<!--                </div>-->
<!---->
<!---->
<!--                <dt>--><?php //echo $this->formLabel($form->get('identity')) ?><!--</dt>-->
<!--                <dd>--><?php //echo $this->formInput($form->get('identity')) ?><!--</dd>-->
<!--                <div class="form-group">-->
<!--                    <input type="password" class="form-control" placeholder="Password" required="" --><?php //echo $this->formInput($form->get('credential')) ?>
<!--                </div>-->
<!--                <dt><label>--><?php //echo 'Password'; ?><!--</label></dt>-->
<!--                <dd>--><?php //echo $this->formInput($form->get('credential')) ?><!--</dd>-->
<!---->
<!--                --><?php //if ($this->redirect): ?>
<!--                    <input type="hidden" name="redirect" value="--><?php //echo 'Sign In'; ?><!--" />-->
<!--                --><?php //endif ?>
<!---->
<!--                <dd>--><?php //echo $this->formButton($form->get('submit')) ?><!--</dd>-->
<!--            </dl>-->
<!---->
<!--            --><?php //echo $this->form()->closeTag() ?>
<!---->
<!---->
<!---->
<!--                    <button type="submit" class="btn btn-primary block full-width m-b">Login</button>-->
<!---->
<!--                    <a href="--><?php //echo $this->url('zfcuser/changepassword') ?><!--">-->
<!--                        <small>Forgot password?</small>-->
<!--                    </a>-->
<!---->
<!--                    <p class="text-muted text-center">-->
<!--                        <small>Do not have an account?</small>-->
<!--                    </p>-->
<!--                    <a class="btn btn-sm btn-white btn-block" href="--><?php //echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?><!--" --><?php //if ($this->enableRegistration) : ?>
<!--                        <a href="--><?php //echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?><!--">Create an account</a>-->
<!--                --><?php //endif; ?>
<!--                </form>-->
<!--                --><?php //if ($this->enableRegistration) : ?>
<!--                    Not registered? <a href="--><?php //echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?><!--">Sign up!</a>-->
<!--                --><?php //endif; ?>
                
            </div>
        </div>
    </div>
    <hr/>

</div>

